export const ViewConfig = {
  gridRowActiveMode: 2,
  rowEditState: false,
  viewCodeName: 'OrgDataGridView',
  viewName: 'OrgDataGridView',
  viewCaption: '组织数据',
  height: '0',
  width: '0',
  viewMsgGroup: '',
  viewUIActions: '[net.ibizsys.model.app.view.PSAppViewUIActionImpl@2679311f, net.ibizsys.model.app.view.PSAppViewUIActionImpl@287f7811, net.ibizsys.model.app.view.PSAppViewUIActionImpl@451f87af, net.ibizsys.model.app.view.PSAppViewUIActionImpl@2b556bb2, net.ibizsys.model.app.view.PSAppViewUIActionImpl@44cb460e, net.ibizsys.model.app.view.PSAppViewUIActionImpl@17271176, net.ibizsys.model.app.view.PSAppViewUIActionImpl@2e3cdec2, net.ibizsys.model.app.view.PSAppViewUIActionImpl@2e34384c, net.ibizsys.model.app.view.PSAppViewUIActionImpl@3051e0b2, net.ibizsys.model.app.view.PSAppViewUIActionImpl@1f52eb6f, net.ibizsys.model.app.view.PSAppViewUIActionImpl@57d0fc89, net.ibizsys.model.app.view.PSAppViewUIActionImpl@58294867, net.ibizsys.model.app.view.PSAppViewUIActionImpl@67c277a0, net.ibizsys.model.app.view.PSAppViewUIActionImpl@6fc3e1a4]',
  viewSysCss: '',
  viewSysImage: '',
  subCaption: '',
  viewType: 'DEGRIDVIEW',
  viewStyle: 'DEFAULT',
  showCaptionBar: 'DEFAULT',
  viewToolbarModel: [
    { name:'tbitem3',caption:'新建',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'新建',disabled: false, visible: true, iconClass: "fa fa-file-text-o", },
    { name:'tbitem4',caption:'编辑',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'编辑',disabled: false, visible: true, iconClass: "fa fa-edit", },
    { name:'tbitem6',caption:'拷贝',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'拷贝',disabled: false, visible: true, iconClass: "fa fa-copy", },
    { name:'tbitem7',caption:'',groupExtractMode:'',itemType:'SEPERATOR',noPrivDisplayMode:'',showIcon:false,showCaption:false,tooltip:'',disabled: false, visible: true, },
    { name:'tbitem8',caption:'删除',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'删除',disabled: false, visible: true, iconClass: "fa fa-remove", },
    { name:'tbitem9',caption:'',groupExtractMode:'',itemType:'SEPERATOR',noPrivDisplayMode:'',showIcon:false,showCaption:false,tooltip:'',disabled: false, visible: true, },
    { name:'tbitem13',caption:'导出',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'导出',disabled: false, visible: true, iconClass: "fa fa-file-excel-o", },
    { name:'tbitem10',caption:'',groupExtractMode:'',itemType:'SEPERATOR',noPrivDisplayMode:'',showIcon:false,showCaption:false,tooltip:'',disabled: false, visible: true, },
    { name:'tbitem16',caption:'其它',groupExtractMode:'',itemType:'ITEMS',noPrivDisplayMode:'',showIcon:true,showCaption:true,tooltip:'其它',disabled: false, visible: true, },
    { name:'tbitem17',caption:'',groupExtractMode:'',itemType:'SEPERATOR',noPrivDisplayMode:'',showIcon:false,showCaption:false,tooltip:'',disabled: false, visible: true, },
    { name:'tbitem19',caption:'过滤',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'过滤',disabled: false, visible: true, iconClass: "fa fa-filter", },
    { name:'tbitem18',caption:'帮助',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'帮助',disabled: false, visible: true, iconClass: "fa fa-question", },
  ],
  controlsAction:{
    grid:{
      loadAction: '',
      removeAction: 'Remove',
      updateAction: '',
      loadDraftAction: '',
      createAction: '',
    },
    searchform:{
      loadAction: '',
      removeAction: '',
      updateAction: '',
      loadDraftAction: '',
      createAction: '',
    },
  }};