export const ViewConfig = {
  viewCodeName: 'ProvinceEditDataView',
  viewName: 'ProvinceEditDataView',
  viewCaption: '省份',
  height: '0',
  width: '0',
  viewMsgGroup: '',
  viewUIActions: '[net.ibizsys.model.app.view.PSAppViewUIActionImpl@10ec523c, net.ibizsys.model.app.view.PSAppViewUIActionImpl@53dfacba, net.ibizsys.model.app.view.PSAppViewUIActionImpl@79767781, net.ibizsys.model.app.view.PSAppViewUIActionImpl@78411116, net.ibizsys.model.app.view.PSAppViewUIActionImpl@aced190, net.ibizsys.model.app.view.PSAppViewUIActionImpl@245a060f, net.ibizsys.model.app.view.PSAppViewUIActionImpl@6edaa77a, net.ibizsys.model.app.view.PSAppViewUIActionImpl@1e63d216, net.ibizsys.model.app.view.PSAppViewUIActionImpl@62ddd21b, net.ibizsys.model.app.view.PSAppViewUIActionImpl@16c3ca31, net.ibizsys.model.app.view.PSAppViewUIActionImpl@2d195ee4, net.ibizsys.model.app.view.PSAppViewUIActionImpl@2d6aca33, net.ibizsys.model.app.view.PSAppViewUIActionImpl@21ab988f, net.ibizsys.model.app.view.PSAppViewUIActionImpl@29314cc9]',
  viewSysCss: '',
  viewSysImage: '',
  subCaption: '',
  viewType: 'DEEDITVIEW',
  viewStyle: 'DEFAULT',
  showCaptionBar: 'DEFAULT',
  viewToolbarModel: [
    { name:'tbitem3',caption:'保存',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'保存',disabled: false, visible: true, iconClass: "fa fa-save", },
    { name:'tbitem4',caption:'保存并新建',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'保存并新建',disabled: false, visible: true, iconClass: "sx-tb-saveandnew", },
    { name:'tbitem5',caption:'保存并关闭',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'保存并关闭',disabled: false, visible: true, iconClass: "sx-tb-saveandclose", },
    { name:'tbitem6',caption:'',groupExtractMode:'',itemType:'SEPERATOR',noPrivDisplayMode:'',showIcon:false,showCaption:false,tooltip:'',disabled: false, visible: true, },
    { name:'tbitem7',caption:'删除并关闭',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'删除并关闭',disabled: false, visible: true, iconClass: "fa fa-remove", },
    { name:'tbitem8',caption:'',groupExtractMode:'',itemType:'SEPERATOR',noPrivDisplayMode:'',showIcon:false,showCaption:false,tooltip:'',disabled: false, visible: true, },
    { name:'tbitem12',caption:'新建',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'新建',disabled: false, visible: true, iconClass: "fa fa-file-text-o", },
    { name:'tbitem13',caption:'',groupExtractMode:'',itemType:'SEPERATOR',noPrivDisplayMode:'',showIcon:false,showCaption:false,tooltip:'',disabled: false, visible: true, },
    { name:'tbitem14',caption:'拷贝',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'拷贝',disabled: false, visible: true, iconClass: "fa fa-copy", },
    { name:'tbitem16',caption:'',groupExtractMode:'',itemType:'SEPERATOR',noPrivDisplayMode:'',showIcon:false,showCaption:false,tooltip:'',disabled: false, visible: true, },
    { name:'tbitem23',caption:'第一个记录',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:false,tooltip:'第一个记录',disabled: false, visible: true, iconClass: "fa fa-fast-backward", },
    { name:'tbitem24',caption:'上一个记录',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:false,tooltip:'上一个记录',disabled: false, visible: true, iconClass: "fa fa-step-backward", },
    { name:'tbitem25',caption:'下一个记录',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:false,tooltip:'下一个记录',disabled: false, visible: true, iconClass: "fa fa-step-forward", },
    { name:'tbitem26',caption:'最后一个记录',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:false,tooltip:'最后一个记录',disabled: false, visible: true, iconClass: "fa fa-fast-forward", },
    { name:'tbitem21',caption:'',groupExtractMode:'',itemType:'SEPERATOR',noPrivDisplayMode:'',showIcon:false,showCaption:false,tooltip:'',disabled: false, visible: true, },
    { name:'tbitem22',caption:'帮助',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'帮助',disabled: false, visible: true, iconClass: "fa fa-question", },
  ],
  controlsAction:{
    form:{
      loadAction: 'Get',
      removeAction: 'Remove',
      updateAction: 'Update',
      loadDraftAction: 'GetDraft',
      createAction: 'GetDraft',
    },
  }};