export const ViewConfig = {
  gridRowActiveMode: 2,
  rowEditState: false,
  viewCodeName: 'LogicValidDataGridView',
  viewName: 'LogicValidDataGridView',
  viewCaption: '示例数据（启用逻辑删除）',
  height: '0',
  width: '0',
  viewMsgGroup: '',
  viewUIActions: '[net.ibizsys.model.app.view.PSAppViewUIActionImpl@2ce45a7b, net.ibizsys.model.app.view.PSAppViewUIActionImpl@153d4abb, net.ibizsys.model.app.view.PSAppViewUIActionImpl@6d4c273c, net.ibizsys.model.app.view.PSAppViewUIActionImpl@5a67e962, net.ibizsys.model.app.view.PSAppViewUIActionImpl@545e57d7, net.ibizsys.model.app.view.PSAppViewUIActionImpl@2bc9a775, net.ibizsys.model.app.view.PSAppViewUIActionImpl@27b000f7, net.ibizsys.model.app.view.PSAppViewUIActionImpl@42f9c19a, net.ibizsys.model.app.view.PSAppViewUIActionImpl@64bfd6fd, net.ibizsys.model.app.view.PSAppViewUIActionImpl@2ab2710, net.ibizsys.model.app.view.PSAppViewUIActionImpl@253b380a, net.ibizsys.model.app.view.PSAppViewUIActionImpl@29c2c826, net.ibizsys.model.app.view.PSAppViewUIActionImpl@3350ebdd, net.ibizsys.model.app.view.PSAppViewUIActionImpl@6818d900]',
  viewSysCss: '',
  viewSysImage: '',
  subCaption: '',
  viewType: 'DEGRIDVIEW',
  viewStyle: 'DEFAULT',
  showCaptionBar: 'DEFAULT',
  viewToolbarModel: [
    { name:'tbitem3',caption:'新建',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'新建',disabled: false, visible: true, iconClass: "fa fa-file-text-o", },
    { name:'tbitem4',caption:'编辑',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'编辑',disabled: false, visible: true, iconClass: "fa fa-edit", },
    { name:'tbitem6',caption:'拷贝',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'拷贝',disabled: false, visible: true, iconClass: "fa fa-copy", },
    { name:'tbitem7',caption:'',groupExtractMode:'',itemType:'SEPERATOR',noPrivDisplayMode:'',showIcon:false,showCaption:false,tooltip:'',disabled: false, visible: true, },
    { name:'tbitem8',caption:'删除',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'删除',disabled: false, visible: true, iconClass: "fa fa-remove", },
    { name:'tbitem9',caption:'',groupExtractMode:'',itemType:'SEPERATOR',noPrivDisplayMode:'',showIcon:false,showCaption:false,tooltip:'',disabled: false, visible: true, },
    { name:'tbitem13',caption:'导出',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'导出',disabled: false, visible: true, iconClass: "fa fa-file-excel-o", },
    { name:'tbitem10',caption:'',groupExtractMode:'',itemType:'SEPERATOR',noPrivDisplayMode:'',showIcon:false,showCaption:false,tooltip:'',disabled: false, visible: true, },
    { name:'tbitem16',caption:'其它',groupExtractMode:'',itemType:'ITEMS',noPrivDisplayMode:'',showIcon:true,showCaption:true,tooltip:'其它',disabled: false, visible: true, },
    { name:'tbitem17',caption:'',groupExtractMode:'',itemType:'SEPERATOR',noPrivDisplayMode:'',showIcon:false,showCaption:false,tooltip:'',disabled: false, visible: true, },
    { name:'tbitem19',caption:'过滤',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'过滤',disabled: false, visible: true, iconClass: "fa fa-filter", },
    { name:'tbitem18',caption:'帮助',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'帮助',disabled: false, visible: true, iconClass: "fa fa-question", },
  ],
  controlsAction:{
    grid:{
      loadAction: '',
      removeAction: 'Remove',
      updateAction: '',
      loadDraftAction: '',
      createAction: '',
    },
    searchform:{
      loadAction: '',
      removeAction: '',
      updateAction: '',
      loadDraftAction: '',
      createAction: '',
    },
  }};