// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppAutoComplete: typeof import('./src/components/editors/app-auto-complete.vue')['default']
    AppCheckbox: typeof import('./src/components/editors/app-checkbox.vue')['default']
    AppCheckboxList: typeof import('./src/components/editors/app-checkbox-list.vue')['default']
    AppCode: typeof import('./src/components/editors/app-code.vue')['default']
    AppDataPicker: typeof import('./src/components/editors/app-data-picker.vue')['default']
    AppDataPickerView: typeof import('./src/components/editors/app-data-picker-view.vue')['default']
    AppDatePicker: typeof import('./src/components/editors/app-date-picker.vue')['default']
    AppDefaultIndexViewLayout: typeof import('./src/components/layout/app-default-index-view-layout.vue')['default']
    AppDropdownList: typeof import('./src/components/editors/app-dropdown-list.vue')['default']
    AppEditViewLayout: typeof import('./src/components/layout/app-edit-view-layout.vue')['default']
    AppFilterTree: typeof import('./src/components/render/app-filter-tree.vue')['default']
    AppFormDruipart: typeof import('./src/components/render/app-form-druipart.vue')['default']
    AppFormGroup: typeof import('./src/components/render/app-form-group.vue')['default']
    AppFormItem: typeof import('./src/components/render/app-form-item.vue')['default']
    AppGridViewLayout: typeof import('./src/components/layout/app-grid-view-layout.vue')['default']
    AppIconText: typeof import('./src/components/render/app-icon-text.vue')['default']
    AppIndexViewBaseLayout: typeof import('./src/components/layout/app-index-view-base-layout.vue')['default']
    AppInput: typeof import('./src/components/editors/app-input.vue')['default']
    AppInputIp: typeof import('./src/components/editors/app-input-ip.vue')['default']
    AppListBox: typeof import('./src/components/editors/app-list-box.vue')['default']
    AppLoading: typeof import('./src/components/render/app-loading.vue')['default']
    AppMenuItem: typeof import('./src/components/render/app-menu-item.vue')['default']
    AppPickUpGridViewLayout: typeof import('./src/components/layout/app-pick-up-grid-view-layout.vue')['default']
    AppPickUpViewLayout: typeof import('./src/components/layout/app-pick-up-view-layout.vue')['default']
    AppQuickGroup: typeof import('./src/components/render/app-quick-group.vue')['default']
    AppRadioGroup: typeof import('./src/components/editors/app-radio-group.vue')['default']
    AppRating: typeof import('./src/components/editors/app-rating.vue')['default']
    AppRaw: typeof import('./src/components/editors/app-raw.vue')['default']
    AppRichText: typeof import('./src/components/editors/app-rich-text.vue')['default']
    AppSlider: typeof import('./src/components/editors/app-slider.vue')['default']
    AppSpan: typeof import('./src/components/editors/app-span.vue')['default']
    AppStepper: typeof import('./src/components/editors/app-stepper.vue')['default']
    AppSwitch: typeof import('./src/components/editors/app-switch.vue')['default']
    AppToolbar: typeof import('./src/components/render/app-toolbar.vue')['default']
    AppTreeExpViewLayout: typeof import('./src/components/layout/app-tree-exp-view-layout.vue')['default']
    AppUpload: typeof import('./src/components/editors/app-upload.vue')['default']
    AppUser: typeof import('./src/components/render/app-user.vue')['default']
    AppViewBaseLayout: typeof import('./src/components/layout/app-view-base-layout.vue')['default']
  }
}

export { }
