export const ViewConfig = {
  gridRowActiveMode: 2,
  rowEditState: false,
  viewCodeName: 'ACTIVITYGridView',
  viewName: 'ACTIVITYGridView',
  viewCaption: '活动',
  height: '0',
  width: '0',
  viewMsgGroup: '',
  viewUIActions: '[net.ibizsys.model.app.view.PSAppViewUIActionImpl@7573e12f, net.ibizsys.model.app.view.PSAppViewUIActionImpl@51b1a8f6, net.ibizsys.model.app.view.PSAppViewUIActionImpl@2a389173, net.ibizsys.model.app.view.PSAppViewUIActionImpl@213860b8, net.ibizsys.model.app.view.PSAppViewUIActionImpl@4ba89729, net.ibizsys.model.app.view.PSAppViewUIActionImpl@178270b2, net.ibizsys.model.app.view.PSAppViewUIActionImpl@795fd838, net.ibizsys.model.app.view.PSAppViewUIActionImpl@1b005a0b, net.ibizsys.model.app.view.PSAppViewUIActionImpl@141e879d, net.ibizsys.model.app.view.PSAppViewUIActionImpl@109d724c, net.ibizsys.model.app.view.PSAppViewUIActionImpl@1704f67f, net.ibizsys.model.app.view.PSAppViewUIActionImpl@e4d2696, net.ibizsys.model.app.view.PSAppViewUIActionImpl@6e0f7aad, net.ibizsys.model.app.view.PSAppViewUIActionImpl@15fb7a32]',
  viewSysCss: '',
  viewSysImage: '',
  subCaption: '',
  viewType: 'DEGRIDVIEW',
  viewStyle: 'DEFAULT',
  showCaptionBar: 'DEFAULT',
  viewToolbarModel: [
    { name:'tbitem3',caption:'新建',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'新建',disabled: false, visible: true, iconClass: "fa fa-file-text-o", },
    { name:'tbitem4',caption:'编辑',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'编辑',disabled: false, visible: true, iconClass: "fa fa-edit", },
    { name:'tbitem6',caption:'拷贝',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'拷贝',disabled: false, visible: true, iconClass: "fa fa-copy", },
    { name:'tbitem7',caption:'',groupExtractMode:'',itemType:'SEPERATOR',noPrivDisplayMode:'',showIcon:false,showCaption:false,tooltip:'',disabled: false, visible: true, },
    { name:'tbitem8',caption:'删除',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'删除',disabled: false, visible: true, iconClass: "fa fa-remove", },
    { name:'tbitem9',caption:'',groupExtractMode:'',itemType:'SEPERATOR',noPrivDisplayMode:'',showIcon:false,showCaption:false,tooltip:'',disabled: false, visible: true, },
    { name:'tbitem13',caption:'导出',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'导出',disabled: false, visible: true, iconClass: "fa fa-file-excel-o", },
    { name:'tbitem10',caption:'',groupExtractMode:'',itemType:'SEPERATOR',noPrivDisplayMode:'',showIcon:false,showCaption:false,tooltip:'',disabled: false, visible: true, },
    { name:'tbitem16',caption:'其它',groupExtractMode:'',itemType:'ITEMS',noPrivDisplayMode:'',showIcon:true,showCaption:true,tooltip:'其它',disabled: false, visible: true, },
    { name:'tbitem17',caption:'',groupExtractMode:'',itemType:'SEPERATOR',noPrivDisplayMode:'',showIcon:false,showCaption:false,tooltip:'',disabled: false, visible: true, },
    { name:'tbitem19',caption:'过滤',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'过滤',disabled: false, visible: true, iconClass: "fa fa-filter", },
    { name:'tbitem18',caption:'帮助',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'帮助',disabled: false, visible: true, iconClass: "fa fa-question", },
  ],
  controlsAction:{
    grid:{
      loadAction: '',
      removeAction: 'Remove',
      updateAction: '',
      loadDraftAction: '',
      createAction: '',
    },
    searchform:{
      loadAction: '',
      removeAction: '',
      updateAction: '',
      loadDraftAction: '',
      createAction: '',
    },
  }};