import { IParam } from '@ibiz-core';
export const CtrlConfig = {
  controlCodeName: "LineEdit",
  controlName: "grid",
  items: [],
  dataAgg: [],
  selectedRowKeys: [],
  aggMode: "NONE",
  noSort: false,
  minorSortDir: "",
  minorSortPSDEF: "",
  enablePagingBar: false,
  pagination: false,
  columnsModel: [
{
  title: "产品",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 100,
  resizable: true,
  dataIndex: "productname",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "单价",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 100,
  resizable: true,
  dataIndex: "price",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "数量",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 100,
  resizable: true,
  dataIndex: "qty",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "小计",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 100,
  resizable: true,
  dataIndex: "amount",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "产品标识",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 100,
  resizable: true,
  dataIndex: "productid",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
  ]
};