export const ctrlState = {
  controlCodeName: 'AppNavAppIndexView',
  controlName: 'appmenu',
  defaultOpens: [],
  defaultSelect: [],
  menus: [
{ 
	name: "menuitem1",
	caption: "常规",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "常规",
  funcTag: "",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
  layoutPos: {
    layout: 'TABLE_24COL',
    lg:"24", lgOffset: "0",
    md:"24", mdOffset: "0",
    sm:"24", smOffset: "0",
    xs:"24", xsOffset: "0",
  },
  items: [
{ 
	name: "menuitem4",
	caption: "打开应用视图",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "打开应用视图",
  funcTag: "",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
  layoutPos: {
    layout: 'TABLE_24COL',
    lg:"24", lgOffset: "0",
    md:"24", mdOffset: "0",
    sm:"24", smOffset: "0",
    xs:"24", xsOffset: "0",
  },
},
{ 
	name: "menuitem5",
	caption: "打开HTML页面",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "打开HTML页面",
  funcTag: "",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
  layoutPos: {
    layout: 'TABLE_24COL',
    lg:"24", lgOffset: "0",
    md:"24", mdOffset: "0",
    sm:"24", smOffset: "0",
    xs:"24", xsOffset: "0",
  },
},
  ]
},
{ 
	name: "menuitem2",
	caption: "预置",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "预置",
  funcTag: "",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
  layoutPos: {
    layout: 'TABLE_24COL',
    lg:"24", lgOffset: "0",
    md:"24", mdOffset: "0",
    sm:"24", smOffset: "0",
    xs:"24", xsOffset: "0",
  },
  items: [
{ 
	name: "menuitem6",
	caption: "预置应用功能",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "预置应用功能",
  funcTag: "",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
  layoutPos: {
    layout: 'TABLE_24COL',
    lg:"24", lgOffset: "0",
    md:"24", mdOffset: "0",
    sm:"24", smOffset: "0",
    xs:"24", xsOffset: "0",
  },
},
  ]
},
{ 
	name: "menuitem3",
	caption: "高级",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "高级",
  funcTag: "",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
  layoutPos: {
    layout: 'TABLE_24COL',
    lg:"24", lgOffset: "0",
    md:"24", mdOffset: "0",
    sm:"24", smOffset: "0",
    xs:"24", xsOffset: "0",
  },
  items: [
{ 
	name: "menuitem7",
	caption: "执行JavaScript",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "执行JavaScript",
  funcTag: "",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
  layoutPos: {
    layout: 'TABLE_24COL',
    lg:"24", lgOffset: "0",
    md:"24", mdOffset: "0",
    sm:"24", smOffset: "0",
    xs:"24", xsOffset: "0",
  },
},
  ]
},
  ],
  funcs: [],
};