export const ctrlState = {
  controlCodeName: 'ViewTypeIndexView',
  controlName: 'appmenu',
  defaultOpens: [],
  defaultSelect: [],
  menus: [
{ 
	name: "menuitem26",
	caption: "自定义视图",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "自定义视图",
  funcTag: "",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
  layoutPos: {
    layout: 'TABLE_24COL',
    lg:"", lgOffset: "0",
    md:"24", mdOffset: "0",
    sm:"", smOffset: "0",
    xs:"", xsOffset: "0",
  },
  items: [
{ 
	name: "menuitem27",
	caption: "自定义视图",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "自定义视图",
  funcTag: "AppFunc46",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
  layoutPos: {
    layout: 'TABLE_24COL',
    lg:"", lgOffset: "0",
    md:"24", mdOffset: "0",
    sm:"", smOffset: "0",
    xs:"", xsOffset: "0",
  },
},
  ]
},
{ 
	name: "menuitem13",
	caption: "单项数据视图",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "单项数据视图",
  funcTag: "",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
  layoutPos: {
    layout: 'TABLE_24COL',
    lg:"", lgOffset: "0",
    md:"24", mdOffset: "0",
    sm:"", smOffset: "0",
    xs:"", xsOffset: "0",
  },
  items: [
{ 
	name: "menuitem19",
	caption: "编辑视图",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "编辑视图",
  funcTag: "AppFunc7",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
  layoutPos: {
    layout: 'TABLE_24COL',
    lg:"", lgOffset: "0",
    md:"24", mdOffset: "0",
    sm:"", smOffset: "0",
    xs:"", xsOffset: "0",
  },
},
{ 
	name: "menuitem22",
	caption: "编辑视图（左右关系）",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "编辑视图（左右关系）",
  funcTag: "AppFunc8",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
  layoutPos: {
    layout: 'TABLE_24COL',
    lg:"", lgOffset: "0",
    md:"24", mdOffset: "0",
    sm:"", smOffset: "0",
    xs:"", xsOffset: "0",
  },
},
{ 
	name: "menuitem24",
	caption: "编辑视图（上下关系）",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "编辑视图（上下关系）",
  funcTag: "AppFunc17",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
  layoutPos: {
    layout: 'TABLE_24COL',
    lg:"", lgOffset: "0",
    md:"24", mdOffset: "0",
    sm:"", smOffset: "0",
    xs:"", xsOffset: "0",
  },
},
{ 
	name: "menuitem23",
	caption: "编辑视图（分页关系）",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "编辑视图（分页关系）",
  funcTag: "AppFunc9",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
  layoutPos: {
    layout: 'TABLE_24COL',
    lg:"", lgOffset: "0",
    md:"24", mdOffset: "0",
    sm:"", smOffset: "0",
    xs:"", xsOffset: "0",
  },
},
{ 
	name: "menuitem25",
	caption: "编辑视图（杂项）",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "编辑视图（杂项）",
  funcTag: "AppFunc45",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
  layoutPos: {
    layout: 'TABLE_24COL',
    lg:"", lgOffset: "0",
    md:"24", mdOffset: "0",
    sm:"", smOffset: "0",
    xs:"", xsOffset: "0",
  },
},
  ]
},
{ 
	name: "menuitem1",
	caption: "多数据视图（基础）",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "多数据视图（基础）",
  funcTag: "",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-list-alt",
  layoutPos: {
    layout: 'TABLE_24COL',
    lg:"", lgOffset: "0",
    md:"24", mdOffset: "0",
    sm:"", smOffset: "0",
    xs:"", xsOffset: "0",
  },
  items: [
{ 
	name: "menuitem2",
	caption: "表格视图",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "表格视图",
  funcTag: "AppFunc6",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
  layoutPos: {
    layout: 'TABLE_24COL',
    lg:"", lgOffset: "0",
    md:"24", mdOffset: "0",
    sm:"", smOffset: "0",
    xs:"", xsOffset: "0",
  },
},
{ 
	name: "menuitem3",
	caption: "列表视图",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "列表视图",
  funcTag: "AppFunc10",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
  layoutPos: {
    layout: 'TABLE_24COL',
    lg:"", lgOffset: "0",
    md:"24", mdOffset: "0",
    sm:"", smOffset: "0",
    xs:"", xsOffset: "0",
  },
},
{ 
	name: "menuitem21",
	caption: "卡片视图",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "卡片视图",
  funcTag: "AppFunc11",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
  layoutPos: {
    layout: 'TABLE_24COL',
    lg:"", lgOffset: "0",
    md:"24", mdOffset: "0",
    sm:"", smOffset: "0",
    xs:"", xsOffset: "0",
  },
},
{ 
	name: "menuitem28",
	caption: "多表单编辑视图",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "多表单编辑视图",
  funcTag: "AppFunc49",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
  layoutPos: {
    layout: 'TABLE_24COL',
    lg:"", lgOffset: "0",
    md:"24", mdOffset: "0",
    sm:"", smOffset: "0",
    xs:"", xsOffset: "0",
  },
},
  ]
},
{ 
	name: "menuitem4",
	caption: "多数据视图（高级）",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "多数据视图（高级）",
  funcTag: "",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-edit",
  layoutPos: {
    layout: 'TABLE_24COL',
    lg:"", lgOffset: "0",
    md:"24", mdOffset: "0",
    sm:"", smOffset: "0",
    xs:"", xsOffset: "0",
  },
  items: [
{ 
	name: "menuitem9",
	caption: "日历视图",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "日历视图",
  funcTag: "AppFunc79",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
  layoutPos: {
    layout: 'TABLE_24COL',
    lg:"", lgOffset: "0",
    md:"24", mdOffset: "0",
    sm:"", smOffset: "0",
    xs:"", xsOffset: "0",
  },
},
{ 
	name: "menuitem10",
	caption: "地图视图",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "地图视图",
  funcTag: "",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
  layoutPos: {
    layout: 'TABLE_24COL',
    lg:"", lgOffset: "0",
    md:"24", mdOffset: "0",
    sm:"", smOffset: "0",
    xs:"", xsOffset: "0",
  },
},
  ]
},
{ 
	name: "menuitem5",
	caption: "导航视图",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "导航视图",
  funcTag: "",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-navicon",
  layoutPos: {
    layout: 'TABLE_24COL',
    lg:"", lgOffset: "0",
    md:"24", mdOffset: "0",
    sm:"", smOffset: "0",
    xs:"", xsOffset: "0",
  },
  items: [
{ 
	name: "menuitem29",
	caption: "分页导航",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "分页导航",
  funcTag: "AppFunc66",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
  layoutPos: {
    layout: 'TABLE_24COL',
    lg:"", lgOffset: "0",
    md:"24", mdOffset: "0",
    sm:"", smOffset: "0",
    xs:"", xsOffset: "0",
  },
},
{ 
	name: "menuitem11",
	caption: "树导航",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "树导航",
  funcTag: "AppFunc12",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
  layoutPos: {
    layout: 'TABLE_24COL',
    lg:"", lgOffset: "0",
    md:"24", mdOffset: "0",
    sm:"", smOffset: "0",
    xs:"", xsOffset: "0",
  },
},
{ 
	name: "menuitem15",
	caption: "列表导航",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "列表导航",
  funcTag: "",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
  layoutPos: {
    layout: 'TABLE_24COL',
    lg:"", lgOffset: "0",
    md:"24", mdOffset: "0",
    sm:"", smOffset: "0",
    xs:"", xsOffset: "0",
  },
},
{ 
	name: "menuitem16",
	caption: "表格导航",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "表格导航",
  funcTag: "",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
  layoutPos: {
    layout: 'TABLE_24COL',
    lg:"", lgOffset: "0",
    md:"24", mdOffset: "0",
    sm:"", smOffset: "0",
    xs:"", xsOffset: "0",
  },
},
{ 
	name: "menuitem18",
	caption: "日历导航",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "日历导航",
  funcTag: "",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
  layoutPos: {
    layout: 'TABLE_24COL',
    lg:"", lgOffset: "0",
    md:"24", mdOffset: "0",
    sm:"", smOffset: "0",
    xs:"", xsOffset: "0",
  },
},
{ 
	name: "menuitem17",
	caption: "地图导航",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "地图导航",
  funcTag: "",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
  layoutPos: {
    layout: 'TABLE_24COL',
    lg:"", lgOffset: "0",
    md:"24", mdOffset: "0",
    sm:"", smOffset: "0",
    xs:"", xsOffset: "0",
  },
},
  ]
},
{ 
	name: "menuitem6",
	caption: "选择视图",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "选择视图",
  funcTag: "",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-check-square",
  layoutPos: {
    layout: 'TABLE_24COL',
    lg:"", lgOffset: "0",
    md:"24", mdOffset: "0",
    sm:"", smOffset: "0",
    xs:"", xsOffset: "0",
  },
  items: [
{ 
	name: "menuitem7",
	caption: "单项选择",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "单项选择",
  funcTag: "AppFunc54",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
  layoutPos: {
    layout: 'TABLE_24COL',
    lg:"", lgOffset: "0",
    md:"24", mdOffset: "0",
    sm:"", smOffset: "0",
    xs:"", xsOffset: "0",
  },
},
{ 
	name: "menuitem8",
	caption: "多项选择",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "多项选择",
  funcTag: "AppFunc72",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
  layoutPos: {
    layout: 'TABLE_24COL',
    lg:"", lgOffset: "0",
    md:"24", mdOffset: "0",
    sm:"", smOffset: "0",
    xs:"", xsOffset: "0",
  },
},
{ 
	name: "menuitem12",
	caption: "选择高级",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "选择高级",
  funcTag: "",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
  layoutPos: {
    layout: 'TABLE_24COL',
    lg:"", lgOffset: "0",
    md:"24", mdOffset: "0",
    sm:"", smOffset: "0",
    xs:"", xsOffset: "0",
  },
},
  ]
},
{ 
	name: "menuitem14",
	caption: "统计分析视图",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "统计分析视图",
  funcTag: "",
  hidden: false,
  disableClose: false,
  iconClass: "grid",
  layoutPos: {
    layout: 'TABLE_24COL',
    lg:"", lgOffset: "0",
    md:"24", mdOffset: "0",
    sm:"", smOffset: "0",
    xs:"", xsOffset: "0",
  },
  items: [
{ 
	name: "menuitem20",
	caption: "常规卡片",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "常规卡片",
  funcTag: "",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
  layoutPos: {
    layout: 'TABLE_24COL',
    lg:"", lgOffset: "0",
    md:"24", mdOffset: "0",
    sm:"", smOffset: "0",
    xs:"", xsOffset: "0",
  },
},
  ]
},
{ 
	name: "menuitem31",
	caption: "其它视图",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "其它视图",
  funcTag: "",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
  layoutPos: {
    layout: 'TABLE_24COL',
    lg:"", lgOffset: "0",
    md:"24", mdOffset: "0",
    sm:"", smOffset: "0",
    xs:"", xsOffset: "0",
  },
  items: [
{ 
	name: "menuitem30",
	caption: "打开HTML页面",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "打开HTML页面",
  funcTag: "AppFunc67",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
  layoutPos: {
    layout: 'TABLE_24COL',
    lg:"", lgOffset: "0",
    md:"24", mdOffset: "0",
    sm:"", smOffset: "0",
    xs:"", xsOffset: "0",
  },
},
{ 
	name: "menuitem32",
	caption: "应用门户视图",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "应用门户视图",
  funcTag: "AppFunc87",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
  layoutPos: {
    layout: 'TABLE_24COL',
    lg:"", lgOffset: "0",
    md:"24", mdOffset: "0",
    sm:"", smOffset: "0",
    xs:"", xsOffset: "0",
  },
},
  ]
},
  ],
  funcs: [],
};