import { IParam } from '@ibiz-core';
export const CtrlConfig = {
  controlCodeName: "CalendarData",
  controlName: "grid",
  items: [],
  dataAgg: [],
  selectedRowKeys: [],
  aggMode: "NONE",
  noSort: false,
  minorSortDir: "",
  minorSortPSDEF: "",
  enablePagingBar: true,
  current: 1,
  pageSize: 20,
  pagination: {
    position: ['bottomRight'],
    defaultPageSize: 20,
    showQuickJumper: true,
    showTotal: (total: number, range: IParam[]) => `${range[0]}-${range[1]} of ${total} items`,
    pageSizeOptions: ['10','20','50','100'],
  },
  columnsModel: [
{
  title: "事项",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 1,
  resizable: true,
  dataIndex: "calendardataname",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "开始时间",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 180,
  resizable: true,
  dataIndex: "begintime",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "结束时间",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 180,
  resizable: true,
  dataIndex: "endtime",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "备注",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 200,
  resizable: true,
  dataIndex: "memo",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
  ]
};