spring:
  cache:
    redis:
      time-to-live: 3600
    caffeine:
      spec: initialCapacity=5,maximumSize=500,expireAfterWrite=3600s
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    lettuce:
      pool:
        max-active: 32
        max-wait: 300ms
        max-idle: 16
        min-idle: 8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


#阿里sentinel熔断器
feign:
  httpclient:
    enabled: true
  sentinel:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
      min-response-size: 10240
    response:
      enabled: true


#Log配置
logging:
  level:
    cn.ibizlab: debug
    cn.ibizlab.sample: debug
    org.springframework.boot.autoconfigure: ERROR

#zuul网关超时设置
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

#系统是否开启权限验证、是否开启缓存
#缓存级别：无缓存(无配置项)、一级缓存(L1)、二级缓存(L2)
ibiz:
  systemid: Sample
  systemname: 示例系统
  enablePermissionValid: true
  cacheLevel: L1 #(L1)一级本地caffeine缓存;(L2)caffeine缓存+Redis缓存


### 启用Gzip压缩
server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 10240


#zuul网关路由设置
zuul:
  routes:
    wfcore:
      path: /wfcore/**
      serviceId: ${ibiz.ref.service.wf:ibzwf-api}}
      stripPrefix: true
    loginv7:
      path: /v7/login
      serviceId: ${ibiz.ref.service.uaa:ibzuaa-api}}
      stripPrefix: false
    changepwd:
      path: /v7/changepwd
      serviceId: ${ibiz.ref.service.uaa:ibzuaa-api}}
      stripPrefix: false
    uaa:
      path: /uaa/**
      serviceId: ${ibiz.ref.service.uaa:ibzuaa-api}}
      stripPrefix: false
    config:
      path: /configs/**
      serviceId: ${ibiz.ref.service.uaa:ibzuaa-api}}
      stripPrefix: false
    oucore:
      path: /ibzorganizations/**
      serviceId: ${ibiz.ref.service.ou:ibzou-api}}
      stripPrefix: false
    oudict:
      path: /dictionarys/**/Ibzou**
      serviceId: ${ibiz.ref.service.ou:ibzou-api}}
      stripPrefix: false
    ou:
      path: /ibzdepartments/**
      serviceId: ${ibiz.ref.service.ou:ibzou-api}}
      stripPrefix: false
    uaadict:
      path: /dictionarys/**/SysOperator
      serviceId: ${ibiz.ref.service.uaa:ibzuaa-api}}
      stripPrefix: false
    dict:
      path: /dictionarys/**
      serviceId: ${ibiz.ref.service.dict:ibzdict-api}}
      stripPrefix: false
    disk:
      path: /net-disk/**
      serviceId: ${ibiz.ref.service.disk:ibzdisk-api}}
      stripPrefix: false
    ou_sys_org:
      path: /sysorganizations/**
      serviceId: ${ibiz.ref.service.ou:ibzou-api}}
      stripPrefix: false
    ou_sys_dept:
      path: /sysdepartments/**
      serviceId: ${ibiz.ref.service.ou:ibzou-api}}
      stripPrefix: false
    lite-core:
      path: /lite/**
      serviceId: ${ibiz.ref.service.lite:ibzlite-api}}
      stripPrefix: false
    sysauthlog:
      path: /sysauthlogs
      serviceId: ${ibiz.ref.service.uaa:ibzuaa-api}}
      stripPrefix: false
    r8mob-orderrepdata:
      path: /orderrepdatas/**
      serviceId: ${ibiz.ref.service.sample-sampleapi:sample-sampleapi}
      stripPrefix: false
    r8mob-example2:
      path: /example2s/**
      serviceId: ${ibiz.ref.service.sample-sampleapi:sample-sampleapi}
      stripPrefix: false
    r8mob-calculator:
      path: /calculators/**
      serviceId: ${ibiz.ref.service.sample-sampleapi:sample-sampleapi}
      stripPrefix: false
    r8mob-counterdata2:
      path: /counterdata2s/**
      serviceId: ${ibiz.ref.service.sample-sampleapi:sample-sampleapi}
      stripPrefix: false
    r8mob-counterdata:
      path: /counterdatas/**
      serviceId: ${ibiz.ref.service.sample-sampleapi:sample-sampleapi}
      stripPrefix: false
    r8mob-persondata:
      path: /peopledata/**
      serviceId: ${ibiz.ref.service.sample-sampleapi:sample-sampleapi}
      stripPrefix: false
    r8mob-deptdata:
      path: /deptdatas/**
      serviceId: ${ibiz.ref.service.sample-sampleapi:sample-sampleapi}
      stripPrefix: false
    r8mob-editorvalue:
      path: /editorvalues/**
      serviceId: ${ibiz.ref.service.sample-sampleapi:sample-sampleapi}
      stripPrefix: false
    r8mob-customer:
      path: /customers/**
      serviceId: ${ibiz.ref.service.sample-sampleapi:sample-sampleapi}
      stripPrefix: false
    r8mob-orgdata:
      path: /orgdatas/**
      serviceId: ${ibiz.ref.service.sample-sampleapi:sample-sampleapi}
      stripPrefix: false
    r8mob-kanbandata:
      path: /kanbandatas/**
      serviceId: ${ibiz.ref.service.sample-sampleapi:sample-sampleapi}
      stripPrefix: false
    r8mob-impexpdata:
      path: /impexpdatas/**
      serviceId: ${ibiz.ref.service.sample-sampleapi:sample-sampleapi}
      stripPrefix: false
    r8mob-activity:
      path: /activities/**
      serviceId: ${ibiz.ref.service.sample-sampleapi:sample-sampleapi}
      stripPrefix: false
    r8mob-mapdata:
      path: /mapdatas/**
      serviceId: ${ibiz.ref.service.sample-sampleapi:sample-sampleapi}
      stripPrefix: false
    r8mob-product:
      path: /products/**
      serviceId: ${ibiz.ref.service.sample-sampleapi:sample-sampleapi}
      stripPrefix: false
    r8mob-city:
      path: /cities/**
      serviceId: ${ibiz.ref.service.sample-sampleapi:sample-sampleapi}
      stripPrefix: false
    r8mob-calendardata:
      path: /calendardatas/**
      serviceId: ${ibiz.ref.service.sample-sampleapi:sample-sampleapi}
      stripPrefix: false
    r8mob-opportunity:
      path: /opportunities/**
      serviceId: ${ibiz.ref.service.sample-sampleapi:sample-sampleapi}
      stripPrefix: false
    r8mob-contact:
      path: /contacts/**
      serviceId: ${ibiz.ref.service.sample-sampleapi:sample-sampleapi}
      stripPrefix: false
    r8mob-chartdata:
      path: /chartdatas/**
      serviceId: ${ibiz.ref.service.sample-sampleapi:sample-sampleapi}
      stripPrefix: false
    r8mob-category:
      path: /categories/**
      serviceId: ${ibiz.ref.service.sample-sampleapi:sample-sampleapi}
      stripPrefix: false
    r8mob-province:
      path: /provinces/**
      serviceId: ${ibiz.ref.service.sample-sampleapi:sample-sampleapi}
      stripPrefix: false
    r8mob-dynadashboard:
      path: /dynadashboards/**
      serviceId: ${ibiz.ref.service.sample-sampleapi:sample-sampleapi}
      stripPrefix: false
    r8mob-event:
      path: /events/**
      serviceId: ${ibiz.ref.service.sample-sampleapi:sample-sampleapi}
      stripPrefix: false
    r8mob-wizarddata:
      path: /wizarddatas/**
      serviceId: ${ibiz.ref.service.sample-sampleapi:sample-sampleapi}
      stripPrefix: false
    r8mob-order:
      path: /orders/**
      serviceId: ${ibiz.ref.service.sample-sampleapi:sample-sampleapi}
      stripPrefix: false
    r8mob-orderdetail:
      path: /orderdetails/**
      serviceId: ${ibiz.ref.service.sample-sampleapi:sample-sampleapi}
      stripPrefix: false
    r8mob-viewmsgdata:
      path: /viewmsgdatas/**
      serviceId: ${ibiz.ref.service.sample-sampleapi:sample-sampleapi}
      stripPrefix: false
    r8mob-productcategory:
      path: /productcategories/**
      serviceId: ${ibiz.ref.service.sample-sampleapi:sample-sampleapi}
      stripPrefix: false
    r8mob-district:
      path: /districts/**
      serviceId: ${ibiz.ref.service.sample-sampleapi:sample-sampleapi}
      stripPrefix: false
    r8mob-samplever:
      path: /samplevers/**
      serviceId: ${ibiz.ref.service.sample-sampleapi:sample-sampleapi}
      stripPrefix: false
    r8mob-example:
      path: /examples/**
      serviceId: ${ibiz.ref.service.sample-sampleapi:sample-sampleapi}
      stripPrefix: false
  sensitive-headers:
    - Cookie,Set-Cookie,Authorization
