export const ViewConfig = {
  gridRowActiveMode: 2,
  rowEditState: false,
  viewCodeName: 'ProductGridDataView',
  viewName: 'ProductGridDataView',
  viewCaption: '产品',
  height: '0',
  width: '0',
  viewMsgGroup: '',
  viewUIActions: '[net.ibizsys.model.app.view.PSAppViewUIActionImpl@63ec445c, net.ibizsys.model.app.view.PSAppViewUIActionImpl@3104351d, net.ibizsys.model.app.view.PSAppViewUIActionImpl@77d18d0b, net.ibizsys.model.app.view.PSAppViewUIActionImpl@7a344b65, net.ibizsys.model.app.view.PSAppViewUIActionImpl@7b7b3edb, net.ibizsys.model.app.view.PSAppViewUIActionImpl@6b474074, net.ibizsys.model.app.view.PSAppViewUIActionImpl@108531c2, net.ibizsys.model.app.view.PSAppViewUIActionImpl@48b22fd4, net.ibizsys.model.app.view.PSAppViewUIActionImpl@6a9d5dff, net.ibizsys.model.app.view.PSAppViewUIActionImpl@3b08f438, net.ibizsys.model.app.view.PSAppViewUIActionImpl@2bac9ba, net.ibizsys.model.app.view.PSAppViewUIActionImpl@5b2f8ab6, net.ibizsys.model.app.view.PSAppViewUIActionImpl@5bdd5689, net.ibizsys.model.app.view.PSAppViewUIActionImpl@2788d0fe]',
  viewSysCss: '',
  viewSysImage: '',
  subCaption: '',
  viewType: 'DEGRIDVIEW',
  viewStyle: 'DEFAULT',
  showCaptionBar: 'DEFAULT',
  viewToolbarModel: [
    { name:'tbitem3',caption:'新建',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'新建',disabled: false, visible: true, iconClass: "fa fa-file-text-o", },
    { name:'tbitem4',caption:'编辑',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'编辑',disabled: false, visible: true, iconClass: "fa fa-edit", },
    { name:'tbitem6',caption:'拷贝',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'拷贝',disabled: false, visible: true, iconClass: "fa fa-copy", },
    { name:'tbitem7',caption:'',groupExtractMode:'',itemType:'SEPERATOR',noPrivDisplayMode:'',showIcon:false,showCaption:false,tooltip:'',disabled: false, visible: true, },
    { name:'tbitem8',caption:'删除',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'删除',disabled: false, visible: true, iconClass: "fa fa-remove", },
    { name:'tbitem9',caption:'',groupExtractMode:'',itemType:'SEPERATOR',noPrivDisplayMode:'',showIcon:false,showCaption:false,tooltip:'',disabled: false, visible: true, },
    { name:'tbitem13',caption:'导出',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'导出',disabled: false, visible: true, iconClass: "fa fa-file-excel-o", },
    { name:'tbitem10',caption:'',groupExtractMode:'',itemType:'SEPERATOR',noPrivDisplayMode:'',showIcon:false,showCaption:false,tooltip:'',disabled: false, visible: true, },
    { name:'tbitem16',caption:'其它',groupExtractMode:'',itemType:'ITEMS',noPrivDisplayMode:'',showIcon:true,showCaption:true,tooltip:'其它',disabled: false, visible: true, },
    { name:'tbitem17',caption:'',groupExtractMode:'',itemType:'SEPERATOR',noPrivDisplayMode:'',showIcon:false,showCaption:false,tooltip:'',disabled: false, visible: true, },
    { name:'tbitem19',caption:'过滤',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'过滤',disabled: false, visible: true, iconClass: "fa fa-filter", },
    { name:'tbitem18',caption:'帮助',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'帮助',disabled: false, visible: true, iconClass: "fa fa-question", },
  ],
  controlsAction:{
  }};