import { IParam } from '@ibiz-core';
export const CtrlConfig = {
  controlCodeName: "Roweditgrid",
  controlName: "grid",
  items: [],
  dataAgg: [],
  selectedRowKeys: [],
  aggMode: "PAGE",
  noSort: false,
  minorSortDir: "",
  minorSortPSDEF: "",
  enablePagingBar: false,
  pagination: false,
  columnsModel: [
{
  title: "图表名称",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 150,
  resizable: true,
  dataIndex: "chartdataname",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "图表时间",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 200,
  resizable: true,
  dataIndex: "chartdate",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "数据分类",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 100,
  resizable: true,
  dataIndex: "datatype",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "年份",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 100,
  resizable: true,
  dataIndex: "year",
  ellipsis: true,
  enableSort: true,
  aggMode: "SUM",
},
{
  title: "数据",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 100,
  resizable: true,
  dataIndex: "data",
  ellipsis: true,
  enableSort: true,
  aggMode: "SUM",
},
{
  title: "数据时间",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 100,
  resizable: true,
  dataIndex: "datetime",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "更新人",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 100,
  resizable: true,
  dataIndex: "updateman",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "更新时间",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 100,
  resizable: true,
  dataIndex: "updatedate",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
  ]
};