import { IParam } from '@ibiz-core';
export const CtrlConfig = {
  controlCodeName: "Main",
  controlName: "grid",
  items: [],
  dataAgg: [],
  selectedRowKeys: [],
  aggMode: "NONE",
  noSort: false,
  minorSortDir: "",
  minorSortPSDEF: "",
  enablePagingBar: true,
  current: 1,
  pageSize: 20,
  pagination: {
    position: ['bottomRight'],
    defaultPageSize: 20,
    showQuickJumper: true,
    showTotal: (total: number, range: IParam[]) => `${range[0]}-${range[1]} of ${total} items`,
    pageSizeOptions: ['10','20','50','100'],
  },
  columnsModel: [
{
  title: "客户名称",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 300,
  resizable: true,
  dataIndex: "customername",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "月份",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 100,
  resizable: true,
  dataIndex: "monthval",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "季度",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 100,
  resizable: true,
  dataIndex: "quarterval",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "年份",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 100,
  resizable: true,
  dataIndex: "yearval",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "处理中金额",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 120,
  resizable: true,
  dataIndex: "processingval",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "待支付金额",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 120,
  resizable: true,
  dataIndex: "payingval",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "已完成金额",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 120,
  resizable: true,
  dataIndex: "finishedval",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "合计",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 100,
  resizable: true,
  dataIndex: "totalval",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
  ]
};