export const ViewConfig = {
    viewCodeName: 'OPPORTUNITYEditView',
    viewName: 'OPPORTUNITYEditView',
    viewCaption: '商机',
    height: '0',
    width: '0',
    viewMsgGroup: '',
    viewUIActions: '[net.ibizsys.model.app.view.PSAppViewUIActionImpl@7c211fd0, net.ibizsys.model.app.view.PSAppViewUIActionImpl@7004e3d, net.ibizsys.model.app.view.PSAppViewUIActionImpl@2d84cb86, net.ibizsys.model.app.view.PSAppViewUIActionImpl@71a3a190, net.ibizsys.model.app.view.PSAppViewUIActionImpl@588ffeb, net.ibizsys.model.app.view.PSAppViewUIActionImpl@7c28c1, net.ibizsys.model.app.view.PSAppViewUIActionImpl@baf1bb3, net.ibizsys.model.app.view.PSAppViewUIActionImpl@67ec8477, net.ibizsys.model.app.view.PSAppViewUIActionImpl@25d958c6, net.ibizsys.model.app.view.PSAppViewUIActionImpl@4482469c, net.ibizsys.model.app.view.PSAppViewUIActionImpl@3703bf3c, net.ibizsys.model.app.view.PSAppViewUIActionImpl@34cf5a97, net.ibizsys.model.app.view.PSAppViewUIActionImpl@5b3f3ba0, net.ibizsys.model.app.view.PSAppViewUIActionImpl@ddf20fd]',
    viewSysCss: '',
    viewSysImage: '',
    subCaption: '',
    viewType: 'DEEDITVIEW',
    viewStyle: 'DEFAULT',
    showCaptionBar: 'DEFAULT',
        editviewtoolbar:{
        name:'toolbar',
        items:[
            { name:'tbitem3',caption:'保存',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'保存' },
            { name:'tbitem4',caption:'保存并新建',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'保存并新建' },
            { name:'tbitem5',caption:'保存并关闭',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'保存并关闭' },
            { name:'tbitem6',caption:'',groupExtractMode:'',itemType:'SEPERATOR',noPrivDisplayMode:'',showIcon:false,showCaption:false,tooltip:'' },
            { name:'tbitem7',caption:'删除并关闭',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'删除并关闭' },
            { name:'tbitem8',caption:'',groupExtractMode:'',itemType:'SEPERATOR',noPrivDisplayMode:'',showIcon:false,showCaption:false,tooltip:'' },
            { name:'tbitem12',caption:'新建',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'新建' },
            { name:'tbitem13',caption:'',groupExtractMode:'',itemType:'SEPERATOR',noPrivDisplayMode:'',showIcon:false,showCaption:false,tooltip:'' },
            { name:'tbitem14',caption:'拷贝',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'拷贝' },
            { name:'tbitem16',caption:'',groupExtractMode:'',itemType:'SEPERATOR',noPrivDisplayMode:'',showIcon:false,showCaption:false,tooltip:'' },
            { name:'tbitem23',caption:'第一个记录',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:false,tooltip:'第一个记录' },
            { name:'tbitem24',caption:'上一个记录',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:false,tooltip:'上一个记录' },
            { name:'tbitem25',caption:'下一个记录',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:false,tooltip:'下一个记录' },
            { name:'tbitem26',caption:'最后一个记录',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:false,tooltip:'最后一个记录' },
            { name:'tbitem21',caption:'',groupExtractMode:'',itemType:'SEPERATOR',noPrivDisplayMode:'',showIcon:false,showCaption:false,tooltip:'' },
            { name:'tbitem22',caption:'帮助',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'帮助' },
        ]
    },
    controlsAction:{
      EditViewtoolbar:{
        loadAction: '',
        removeAction: '',
        updateAction: '',
        loadDraftAction: '',
        createAction: '',
      },
      Main:{
        loadAction: 'Get',
        removeAction: 'Remove',
        updateAction: 'Update',
        loadDraftAction: 'GetDraft',
        createAction: 'GetDraft',
      },
    }};