import { IParam } from '@ibiz-core';
export const CtrlConfig = {
  controlCodeName: "Main_2",
  controlName: "grid",
  items: [],
  dataAgg: [],
  selectedRowKeys: [],
  aggMode: "PAGE",
  noSort: false,
  minorSortDir: "",
  minorSortPSDEF: "",
  enablePagingBar: false,
  pagination: false,
  columnsModel: [
{
  title: "图表名称",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 150,
  resizable: true,
  dataIndex: "chartname",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "图表时间",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 200,
  resizable: true,
  dataIndex: "date",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "数据分类",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 100,
  resizable: true,
  dataIndex: "type",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "年份",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 100,
  resizable: true,
  dataIndex: "nian",
  ellipsis: true,
  enableSort: true,
  aggMode: "AVG",
},
{
  title: "数据",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 100,
  resizable: true,
  dataIndex: "testdata",
  ellipsis: true,
  enableSort: true,
  aggMode: "SUM",
},
{
  title: "数据时间",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 200,
  resizable: true,
  dataIndex: "time",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "更新人",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 150,
  resizable: true,
  dataIndex: "person",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "更新时间",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 150,
  resizable: true,
  dataIndex: "updatedate",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "操作",
  columnType: "UAGRIDCOLUMN",
  align: "right",
  width: 100,
  resizable: true,
  fixed: "right",
  dataIndex: "uagridcolumn1",
  ellipsis: true,
  enableSort: false,
  aggMode: "NONE",
},
  ]
};