export const ctrlState = {
  controlCodeName: 'MobQuickMenu',
  controlName: 'db_appmenu1_appmenu',
  defaultOpens: [],
  defaultSelect: [],
  menus: [
      { 
      	name: "menuitem1",
      	caption: "表单",
      	itemType: "MENUITEM",
        expanded: false,
      	tooltip: "图表实体编辑视图",
        funcTag: "AppFunc3",
        hidden: false,
        disableClose: false,
        iconClass: "ribbon",
        itemSysCss: 'test',
        layoutPos: {
          layout: 'TABLE_24COL',
          lg:"", lgOffset: "0",
          md:"24", mdOffset: "0",
          sm:"", smOffset: "0",
          xs:"", xsOffset: "0",
        },
      },
      { 
      	name: "menuitem2",
      	caption: "多数据视图",
      	itemType: "MENUITEM",
        expanded: false,
      	tooltip: "多数据视图",
        funcTag: "OpenProvince",
        hidden: false,
        disableClose: false,
        iconClass: "fa fa-cogs",
        layoutPos: {
          layout: 'TABLE_24COL',
          lg:"", lgOffset: "0",
          md:"24", mdOffset: "0",
          sm:"", smOffset: "0",
          xs:"", xsOffset: "0",
        },
      },
      { 
      	name: "menuitem3",
      	caption: "面板测试",
      	itemType: "MENUITEM",
        expanded: false,
      	tooltip: "面板测试",
        funcTag: "AppFunc2",
        hidden: false,
        disableClose: false,
        iconClass: "fa fa-eye",
        layoutPos: {
          layout: 'TABLE_24COL',
          lg:"", lgOffset: "0",
          md:"24", mdOffset: "0",
          sm:"", smOffset: "0",
          xs:"", xsOffset: "0",
        },
      },
      { 
      	name: "menuitem4",
      	caption: "面板视图",
      	itemType: "MENUITEM",
        expanded: false,
      	tooltip: "面板视图",
        funcTag: "AppFunc6",
        hidden: false,
        disableClose: false,
        iconClass: "fa fa-cogs",
        layoutPos: {
          layout: 'TABLE_24COL',
          lg:"", lgOffset: "0",
          md:"24", mdOffset: "0",
          sm:"", smOffset: "0",
          xs:"", xsOffset: "0",
        },
      },
      { 
      	name: "menuitem5",
      	caption: "日历",
      	itemType: "MENUITEM",
        expanded: false,
      	tooltip: "日历",
        funcTag: "AppFunc7",
        hidden: false,
        disableClose: false,
        iconClass: "fa fa-cogs",
        layoutPos: {
          layout: 'TABLE_24COL',
          lg:"", lgOffset: "0",
          md:"24", mdOffset: "0",
          sm:"", smOffset: "0",
          xs:"", xsOffset: "0",
        },
      },
      { 
      	name: "menuitem6",
      	caption: "树视图",
      	itemType: "MENUITEM",
        expanded: false,
      	tooltip: "树视图",
        funcTag: "AppFunc8",
        hidden: false,
        disableClose: false,
        iconClass: "fa fa-cogs",
        layoutPos: {
          layout: 'TABLE_24COL',
          lg:"", lgOffset: "0",
          md:"24", mdOffset: "0",
          sm:"", smOffset: "0",
          xs:"", xsOffset: "0",
        },
      },
      { 
      	name: "menuitem7",
      	caption: "图表",
      	itemType: "MENUITEM",
        expanded: false,
      	tooltip: "图表",
        funcTag: "AppFunc9",
        hidden: false,
        disableClose: false,
        iconClass: "fa fa-heart",
        layoutPos: {
          layout: 'TABLE_24COL',
          lg:"", lgOffset: "0",
          md:"24", mdOffset: "0",
          sm:"", smOffset: "0",
          xs:"", xsOffset: "0",
        },
      },
      { 
      	name: "menuitem8",
      	caption: "地图",
      	itemType: "MENUITEM",
        expanded: false,
      	tooltip: "地图",
        funcTag: "AppFunc10",
        hidden: false,
        disableClose: false,
        iconClass: "fa fa-cogs",
        layoutPos: {
          layout: 'TABLE_24COL',
          lg:"", lgOffset: "0",
          md:"24", mdOffset: "0",
          sm:"", smOffset: "0",
          xs:"", xsOffset: "0",
        },
      },
      { 
      	name: "menuitem9",
      	caption: "分页导航",
      	itemType: "MENUITEM",
        expanded: false,
      	tooltip: "分页导航",
        funcTag: "AppFunc11",
        hidden: false,
        disableClose: false,
        iconClass: "fa fa-cogs",
        layoutPos: {
          layout: 'TABLE_24COL',
          lg:"", lgOffset: "0",
          md:"24", mdOffset: "0",
          sm:"", smOffset: "0",
          xs:"", xsOffset: "0",
        },
      },
      { 
      	name: "menuitem10",
      	caption: "多表单编辑",
      	itemType: "MENUITEM",
        expanded: false,
      	tooltip: "多表单编辑",
        funcTag: "AppFunc13",
        hidden: false,
        disableClose: false,
        iconClass: "fa fa-cogs",
        layoutPos: {
          layout: 'TABLE_24COL',
          lg:"", lgOffset: "0",
          md:"24", mdOffset: "0",
          sm:"", smOffset: "0",
          xs:"", xsOffset: "0",
        },
      },
      { 
      	name: "menuitem11",
      	caption: "看板视图",
      	itemType: "MENUITEM",
        expanded: false,
      	tooltip: "看板视图",
        funcTag: "AppFunc14",
        hidden: false,
        disableClose: false,
        iconClass: "fa fa-cogs",
        layoutPos: {
          layout: 'TABLE_24COL',
          lg:"", lgOffset: "0",
          md:"24", mdOffset: "0",
          sm:"", smOffset: "0",
          xs:"", xsOffset: "0",
        },
      },
      { 
      	name: "menuitem12",
      	caption: "HTML视图",
      	itemType: "MENUITEM",
        expanded: false,
      	tooltip: "HTML视图",
        funcTag: "AppFunc12",
        hidden: false,
        disableClose: false,
        iconClass: "fa fa-cogs",
        layoutPos: {
          layout: 'TABLE_24COL',
          lg:"", lgOffset: "0",
          md:"24", mdOffset: "0",
          sm:"", smOffset: "0",
          xs:"", xsOffset: "0",
        },
      },
      { 
      	name: "menuitem13",
      	caption: "实体数据看板视图",
      	itemType: "MENUITEM",
        expanded: false,
      	tooltip: "实体数据看板视图",
        funcTag: "AppFunc16",
        hidden: false,
        disableClose: false,
        iconClass: "fa fa-cogs",
        layoutPos: {
          layout: 'TABLE_24COL',
          lg:"", lgOffset: "0",
          md:"24", mdOffset: "0",
          sm:"", smOffset: "0",
          xs:"", xsOffset: "0",
        },
      },
  ],
  funcs: [],
};