export const ctrlState = {
  controlCodeName: 'CounterAppIndexView',
  controlName: 'appmenu',
  defaultOpens: [],
  defaultSelect: [],
  menus: [
      { 
      	name: "menuitem1",
      	caption: "菜单计数器",
      	itemType: "MENUITEM",
        expanded: false,
      	tooltip: "菜单计数器",
        funcTag: "",
        hidden: false,
        disableClose: false,
        openDefault: false,
        iconClass: "fa fa-cogs",
        layoutPos: {
          layout: 'TABLE_24COL',
          lg:"", lgOffset: "0",
          md:"24", mdOffset: "0",
          sm:"", smOffset: "0",
          xs:"", xsOffset: "0",
        },
        items: [
            { 
            	name: "menuitem2",
            	caption: "计数1",
            	itemType: "MENUITEM",
              expanded: false,
            	tooltip: "计数1",
              funcTag: "",
              hidden: false,
              disableClose: false,
              openDefault: false,
              counterId: "countertag",
              iconClass: "fa fa-cogs",
              layoutPos: {
                layout: 'TABLE_24COL',
                lg:"", lgOffset: "0",
                md:"24", mdOffset: "0",
                sm:"", smOffset: "0",
                xs:"", xsOffset: "0",
              },
            },
            { 
            	name: "menuitem3",
            	caption: "计数2",
            	itemType: "MENUITEM",
              expanded: false,
            	tooltip: "计数2",
              funcTag: "",
              hidden: false,
              disableClose: false,
              openDefault: false,
              counterId: "countertag2",
              iconClass: "fa fa-cogs",
              layoutPos: {
                layout: 'TABLE_24COL',
                lg:"", lgOffset: "0",
                md:"24", mdOffset: "0",
                sm:"", smOffset: "0",
                xs:"", xsOffset: "0",
              },
            },
            { 
            	name: "menuitem4",
            	caption: "计数3",
            	itemType: "MENUITEM",
              expanded: false,
            	tooltip: "计数3",
              funcTag: "",
              hidden: false,
              disableClose: false,
              openDefault: false,
              counterId: "countertag3",
              iconClass: "fa fa-cogs",
              layoutPos: {
                layout: 'TABLE_24COL',
                lg:"", lgOffset: "0",
                md:"24", mdOffset: "0",
                sm:"", smOffset: "0",
                xs:"", xsOffset: "0",
              },
            },
        ]
      },
  ],
  funcs: App.getAllFuncs(),
};