export const ctrlState = {
  controlCodeName: 'MobAppMenuForKanBan',
  controlName: 'db_appmenu1_appmenu',
  defaultOpens: [],
  defaultSelect: [],
  menus: [
      { 
      	name: "menuitem1",
      	caption: "多数据视图",
      	itemType: "MENUITEM",
        expanded: false,
      	tooltip: "多数据视图",
        funcTag: "AppFunc2",
        hidden: false,
        disableClose: false,
        openDefault: false,
        iconClass: "fa fa-cogs",
        layoutPos: {
          layout: 'TABLE_24COL',
          lg:"", lgOffset: "0",
          md:"24", mdOffset: "0",
          sm:"", smOffset: "0",
          xs:"", xsOffset: "0",
        },
      },
      { 
      	name: "menuitem2",
      	caption: "树视图",
      	itemType: "MENUITEM",
        expanded: false,
      	tooltip: "树视图",
        funcTag: "AppFunc8",
        hidden: false,
        disableClose: false,
        openDefault: false,
        iconClass: "fa fa-cogs",
        layoutPos: {
          layout: 'TABLE_24COL',
          lg:"", lgOffset: "0",
          md:"24", mdOffset: "0",
          sm:"", smOffset: "0",
          xs:"", xsOffset: "0",
        },
      },
  ],
  funcs: App.getAllFuncs(),
};