export const ctrlState = {
  controlCodeName: 'CtrlTypeIndexView',
  controlName: 'appmenu',
  defaultOpens: [],
  defaultSelect: [],
  menus: [
      { 
      	name: "menuitem1",
      	caption: "单项数据部件",
      	itemType: "MENUITEM",
        expanded: false,
      	tooltip: "单项数据部件",
        funcTag: "",
        hidden: false,
        disableClose: false,
        openDefault: false,
        iconClass: "fa fa-cogs",
        layoutPos: {
          layout: 'TABLE_24COL',
          lg:"", lgOffset: "0",
          md:"24", mdOffset: "0",
          sm:"", smOffset: "0",
          xs:"", xsOffset: "0",
        },
        items: [
            { 
            	name: "menuitem6",
            	caption: "表单",
            	itemType: "MENUITEM",
              expanded: false,
            	tooltip: "表单",
              funcTag: "AppFunc16",
              hidden: false,
              disableClose: false,
              openDefault: false,
              iconClass: "fa fa-cogs",
              layoutPos: {
                layout: 'TABLE_24COL',
                lg:"", lgOffset: "0",
                md:"24", mdOffset: "0",
                sm:"", smOffset: "0",
                xs:"", xsOffset: "0",
              },
            },
            { 
            	name: "menuitem12",
            	caption: "面板",
            	itemType: "MENUITEM",
              expanded: false,
            	tooltip: "面板",
              funcTag: "AppFunc48",
              hidden: false,
              disableClose: false,
              openDefault: false,
              iconClass: "fa fa-cogs",
              layoutPos: {
                layout: 'TABLE_24COL',
                lg:"", lgOffset: "0",
                md:"24", mdOffset: "0",
                sm:"", smOffset: "0",
                xs:"", xsOffset: "0",
              },
            },
        ]
      },
      { 
      	name: "menuitem2",
      	caption: "多数据部件",
      	itemType: "MENUITEM",
        expanded: false,
      	tooltip: "多数据部件",
        funcTag: "",
        hidden: false,
        disableClose: false,
        openDefault: false,
        iconClass: "fa fa-cogs",
        layoutPos: {
          layout: 'TABLE_24COL',
          lg:"", lgOffset: "0",
          md:"24", mdOffset: "0",
          sm:"", smOffset: "0",
          xs:"", xsOffset: "0",
        },
        items: [
            { 
            	name: "menuitem3",
            	caption: "表格",
            	itemType: "MENUITEM",
              expanded: false,
            	tooltip: "表格",
              funcTag: "AppFunc44",
              hidden: false,
              disableClose: false,
              openDefault: false,
              iconClass: "fa fa-cogs",
              layoutPos: {
                layout: 'TABLE_24COL',
                lg:"", lgOffset: "0",
                md:"24", mdOffset: "0",
                sm:"", smOffset: "0",
                xs:"", xsOffset: "0",
              },
            },
            { 
            	name: "menuitem4",
            	caption: "列表",
            	itemType: "MENUITEM",
              expanded: false,
            	tooltip: "列表",
              funcTag: "AppFunc56",
              hidden: false,
              disableClose: false,
              openDefault: false,
              iconClass: "fa fa-cogs",
              layoutPos: {
                layout: 'TABLE_24COL',
                lg:"", lgOffset: "0",
                md:"24", mdOffset: "0",
                sm:"", smOffset: "0",
                xs:"", xsOffset: "0",
              },
            },
            { 
            	name: "menuitem5",
            	caption: "卡片&看板",
            	itemType: "MENUITEM",
              expanded: false,
            	tooltip: "卡片&看板",
              funcTag: "AppFunc58",
              hidden: false,
              disableClose: false,
              openDefault: false,
              iconClass: "fa fa-cogs",
              layoutPos: {
                layout: 'TABLE_24COL',
                lg:"", lgOffset: "0",
                md:"24", mdOffset: "0",
                sm:"", smOffset: "0",
                xs:"", xsOffset: "0",
              },
            },
        ]
      },
      { 
      	name: "menuitem17",
      	caption: "多数据部件（复合数据源）",
      	itemType: "MENUITEM",
        expanded: false,
      	tooltip: "多数据部件（复合数据源）",
        funcTag: "",
        hidden: false,
        disableClose: false,
        openDefault: false,
        iconClass: "fa fa-cogs",
        layoutPos: {
          layout: 'TABLE_24COL',
          lg:"", lgOffset: "0",
          md:"24", mdOffset: "0",
          sm:"", smOffset: "0",
          xs:"", xsOffset: "0",
        },
        items: [
            { 
            	name: "menuitem8",
            	caption: "树视图",
            	itemType: "MENUITEM",
              expanded: false,
            	tooltip: "树视图",
              funcTag: "AppFunc47",
              hidden: false,
              disableClose: false,
              openDefault: false,
              iconClass: "fa fa-cogs",
              layoutPos: {
                layout: 'TABLE_24COL',
                lg:"", lgOffset: "0",
                md:"24", mdOffset: "0",
                sm:"", smOffset: "0",
                xs:"", xsOffset: "0",
              },
            },
            { 
            	name: "menuitem10",
            	caption: "日历",
            	itemType: "MENUITEM",
              expanded: false,
            	tooltip: "日历",
              funcTag: "AppFunc50",
              hidden: false,
              disableClose: false,
              openDefault: false,
              iconClass: "fa fa-cogs",
              layoutPos: {
                layout: 'TABLE_24COL',
                lg:"", lgOffset: "0",
                md:"24", mdOffset: "0",
                sm:"", smOffset: "0",
                xs:"", xsOffset: "0",
              },
            },
        ]
      },
      { 
      	name: "menuitem20",
      	caption: "综合呈现",
      	itemType: "MENUITEM",
        expanded: false,
      	tooltip: "综合呈现",
        funcTag: "",
        hidden: false,
        disableClose: false,
        openDefault: false,
        iconClass: "fa fa-cogs",
        layoutPos: {
          layout: 'TABLE_24COL',
          lg:"", lgOffset: "0",
          md:"24", mdOffset: "0",
          sm:"", smOffset: "0",
          xs:"", xsOffset: "0",
        },
        items: [
            { 
            	name: "menuitem16",
            	caption: "数据看板",
            	itemType: "MENUITEM",
              expanded: false,
            	tooltip: "数据看板",
              funcTag: "AppFunc59",
              hidden: false,
              disableClose: false,
              openDefault: false,
              iconClass: "fa fa-cogs",
              layoutPos: {
                layout: 'TABLE_24COL',
                lg:"", lgOffset: "0",
                md:"24", mdOffset: "0",
                sm:"", smOffset: "0",
                xs:"", xsOffset: "0",
              },
            },
            { 
            	name: "menuitem9",
            	caption: "地图",
            	itemType: "MENUITEM",
              expanded: false,
            	tooltip: "地图",
              funcTag: "AppFunc52",
              hidden: false,
              disableClose: false,
              openDefault: false,
              iconClass: "fa fa-cogs",
              layoutPos: {
                layout: 'TABLE_24COL',
                lg:"", lgOffset: "0",
                md:"24", mdOffset: "0",
                sm:"", smOffset: "0",
                xs:"", xsOffset: "0",
              },
            },
            { 
            	name: "menuitem11",
            	caption: "图表",
            	itemType: "MENUITEM",
              expanded: false,
            	tooltip: "图表",
              funcTag: "AppFunc19",
              hidden: false,
              disableClose: false,
              openDefault: false,
              iconClass: "fa fa-cogs",
              layoutPos: {
                layout: 'TABLE_24COL',
                lg:"", lgOffset: "0",
                md:"24", mdOffset: "0",
                sm:"", smOffset: "0",
                xs:"", xsOffset: "0",
              },
            },
        ]
      },
      { 
      	name: "menuitem13",
      	caption: "其它部件",
      	itemType: "MENUITEM",
        expanded: false,
      	tooltip: "其它部件",
        funcTag: "",
        hidden: false,
        disableClose: false,
        openDefault: false,
        iconClass: "fa fa-cogs",
        layoutPos: {
          layout: 'TABLE_24COL',
          lg:"", lgOffset: "0",
          md:"24", mdOffset: "0",
          sm:"", smOffset: "0",
          xs:"", xsOffset: "0",
        },
        items: [
            { 
            	name: "menuitem14",
            	caption: "搜索表单",
            	itemType: "MENUITEM",
              expanded: false,
            	tooltip: "搜索表单",
              funcTag: "AppFunc60",
              hidden: false,
              disableClose: false,
              openDefault: false,
              iconClass: "fa fa-cogs",
              layoutPos: {
                layout: 'TABLE_24COL',
                lg:"", lgOffset: "0",
                md:"24", mdOffset: "0",
                sm:"", smOffset: "0",
                xs:"", xsOffset: "0",
              },
            },
            { 
            	name: "menuitem15",
            	caption: "工具栏",
            	itemType: "MENUITEM",
              expanded: false,
            	tooltip: "工具栏",
              funcTag: "AppFunc61",
              hidden: false,
              disableClose: false,
              openDefault: false,
              iconClass: "fa fa-cogs",
              layoutPos: {
                layout: 'TABLE_24COL',
                lg:"", lgOffset: "0",
                md:"24", mdOffset: "0",
                sm:"", smOffset: "0",
                xs:"", xsOffset: "0",
              },
            },
            { 
            	name: "menuitem7",
            	caption: "搜索栏",
            	itemType: "MENUITEM",
              expanded: false,
            	tooltip: "搜索栏",
              funcTag: "AppFunc62",
              hidden: false,
              disableClose: false,
              openDefault: false,
              iconClass: "fa fa-cogs",
              layoutPos: {
                layout: 'TABLE_24COL',
                lg:"", lgOffset: "0",
                md:"24", mdOffset: "0",
                sm:"", smOffset: "0",
                xs:"", xsOffset: "0",
              },
            },
            { 
            	name: "menuitem18",
            	caption: "向导面板",
            	itemType: "MENUITEM",
              expanded: false,
            	tooltip: "向导面板",
              funcTag: "AppFunc63",
              hidden: false,
              disableClose: false,
              openDefault: false,
              iconClass: "fa fa-cogs",
              layoutPos: {
                layout: 'TABLE_24COL',
                lg:"", lgOffset: "0",
                md:"24", mdOffset: "0",
                sm:"", smOffset: "0",
                xs:"", xsOffset: "0",
              },
            },
            { 
            	name: "menuitem19",
            	caption: "数据关系部件",
            	itemType: "MENUITEM",
              expanded: false,
            	tooltip: "数据关系部件",
              funcTag: "AppFunc64",
              hidden: false,
              disableClose: false,
              openDefault: false,
              iconClass: "fa fa-cogs",
              layoutPos: {
                layout: 'TABLE_24COL',
                lg:"", lgOffset: "0",
                md:"24", mdOffset: "0",
                sm:"", smOffset: "0",
                xs:"", xsOffset: "0",
              },
            },
        ]
      },
  ],
  funcs: App.getAllFuncs(),
};