import { IParam } from '@ibiz-core';
export const CtrlConfig = {
  controlCodeName: "Layout",
  controlName: "grid",
  items: [],
  dataAgg: [],
  selectedRowKeys: [],
  aggMode: "NONE",
  noSort: false,
  minorSortDir: "",
  minorSortPSDEF: "",
  enablePagingBar: true,
  current: 1,
  pageSize: 20,
  pagination: {
    position: ['bottomRight'],
    defaultPageSize: 20,
    showQuickJumper: true,
    showTotal: (total: number, range: IParam[]) => `${range[0]}-${range[1]} of ${total} items`,
    pageSizeOptions: ['10','20','50','100'],
  },
  columnsModel: [
{
  title: "1*",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 1,
  resizable: true,
  dataIndex: "examplename",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "100宽",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 100,
  resizable: true,
  dataIndex: "fieldx",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "200宽",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 200,
  resizable: true,
  dataIndex: "fieldy",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "300宽",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 300,
  resizable: true,
  dataIndex: "fieldz",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "标题居中",
  columnType: "DEFGRIDCOLUMN",
  align: "center",
  width: 200,
  resizable: true,
  dataIndex: "begintime",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "标题右对齐",
  columnType: "DEFGRIDCOLUMN",
  align: "right",
  width: 200,
  resizable: true,
  dataIndex: "updatedate",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
  ]
};