export const ctrlState = {
  controlCodeName: 'testappmenu',
  controlName: 'db_appmenu1_appmenu',
  defaultOpens: [],
  defaultSelect: [],
  menus: [
      { 
      	name: "menuitem1",
      	caption: "测试菜单项1",
      	itemType: "MENUITEM",
        expanded: false,
      	tooltip: "测试菜单项1",
        funcTag: "AppFunc7",
        hidden: false,
        disableClose: false,
        openDefault: false,
        iconClass: "fa fa-cogs",
        layoutPos: {
          layout: 'TABLE_24COL',
          lg:"", lgOffset: "0",
          md:"24", mdOffset: "0",
          sm:"", smOffset: "0",
          xs:"", xsOffset: "0",
        },
      },
      { 
      	name: "menuitem2",
      	caption: "测试菜单项2",
      	itemType: "MENUITEM",
        expanded: false,
      	tooltip: "测试菜单项2",
        funcTag: "",
        hidden: false,
        disableClose: false,
        openDefault: false,
        iconClass: "fa fa-cogs",
        layoutPos: {
          layout: 'TABLE_24COL',
          lg:"", lgOffset: "0",
          md:"24", mdOffset: "0",
          sm:"", smOffset: "0",
          xs:"", xsOffset: "0",
        },
      },
  ],
  funcs: App.getAllFuncs(),
};