import { IParam } from '@ibiz-core';
export const CtrlConfig = {
  controlCodeName: "Main",
  controlName: "grid",
  items: [],
  dataAgg: [],
  selectedRowKeys: [],
  aggMode: "NONE",
  noSort: false,
  minorSortDir: "",
  minorSortPSDEF: "",
  enablePagingBar: true,
  current: 1,
  pageSize: 20,
  pagination: {
    position: ['bottomRight'],
    defaultPageSize: 20,
    showQuickJumper: true,
    showTotal: (total: number, range: IParam[]) => `${range[0]}-${range[1]} of ${total} items`,
    pageSizeOptions: ['10','20','50','100'],
  },
  columnsModel: [
{
  title: "图表名称",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 150,
  resizable: true,
  dataIndex: "chartdataname",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "图表时间",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 200,
  resizable: true,
  dataIndex: "chartdate",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "数据分类",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 100,
  resizable: true,
  dataIndex: "datatype",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "年份",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 100,
  resizable: true,
  dataIndex: "year",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "数据",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 100,
  resizable: true,
  dataIndex: "data",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "计划收入",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 100,
  resizable: true,
  dataIndex: "planincome",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "实际收入",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 100,
  resizable: true,
  dataIndex: "realincome",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "数据时间",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 200,
  resizable: true,
  dataIndex: "datetime",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "更新人",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 150,
  resizable: true,
  dataIndex: "updateman",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "更新时间",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 150,
  resizable: true,
  dataIndex: "updatedate",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "操作",
  columnType: "UAGRIDCOLUMN",
  align: "right",
  width: 100,
  resizable: true,
  fixed: "right",
  dataIndex: "uagridcolumn1",
  ellipsis: true,
  enableSort: false,
  aggMode: "NONE",
},
  ]
};