import { IParam } from '@ibiz-core';
export const CtrlConfig = {
  controlCodeName: "Main",
  controlName: "grid",
  items: [],
  dataAgg: [],
  selectedRowKeys: [],
  aggMode: "NONE",
  noSort: false,
  minorSortDir: "",
  minorSortPSDEF: "",
  enablePagingBar: true,
  current: 1,
  pageSize: 20,
  pagination: {
    position: ['bottomRight'],
    defaultPageSize: 20,
    showQuickJumper: true,
    showTotal: (total: number, range: IParam[]) => `${range[0]}-${range[1]} of ${total} items`,
    pageSizeOptions: ['10','20','50','100'],
  },
  columnsModel: [
{
  title: "客户名称",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 100,
  resizable: true,
  dataIndex: "customername",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "类型",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 100,
  resizable: true,
  dataIndex: "type",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "上级客户",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 120,
  resizable: true,
  dataIndex: "pcustomername",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "电话",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 150,
  resizable: true,
  dataIndex: "phone",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "手机",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 150,
  resizable: true,
  dataIndex: "mobile",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "电子邮箱",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 150,
  resizable: true,
  dataIndex: "email",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "操作",
  columnType: "UAGRIDCOLUMN",
  align: "right",
  width: 100,
  resizable: true,
  fixed: "right",
  dataIndex: "uagridcolumn1",
  ellipsis: true,
  enableSort: false,
  aggMode: "NONE",
},
  ]
};