export const CtrlConfig = {
  controlCodeName: 'AppIndexView2',
  controlName: 'appmenu',
  defaultOpens: [],
  defaultSelect: [],
  menus: [
{ 
	name: "menuitem1",
	caption: "基础",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "基础",
  funcTag: "",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
{ 
	name: "menuitem2",
	caption: "菜单项",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "菜单项",
  funcTag: "",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
  ],
  funcs: [],
};