export const ctrlState = {
  controlCodeName: 'AppIndexView2',
  controlName: 'appmenu',
  defaultOpens: [],
  defaultSelect: [],
  menus: [
      { 
      	name: "menuitem1",
      	caption: "基础",
      	itemType: "MENUITEM",
        expanded: false,
      	tooltip: "基础",
        funcTag: "",
        hidden: false,
        disableClose: false,
        iconClass: "fa fa-cogs",
        layoutPos: {
          layout: 'TABLE_24COL',
          lg:"", lgOffset: "0",
          md:"24", mdOffset: "0",
          sm:"", smOffset: "0",
          xs:"", xsOffset: "0",
        },
      },
      { 
      	name: "menuitem2",
      	caption: "菜单项",
      	itemType: "MENUITEM",
        expanded: false,
      	tooltip: "菜单项",
        funcTag: "",
        hidden: false,
        disableClose: false,
        iconClass: "fa fa-cogs",
        layoutPos: {
          layout: 'TABLE_24COL',
          lg:"", lgOffset: "0",
          md:"24", mdOffset: "0",
          sm:"", smOffset: "0",
          xs:"", xsOffset: "0",
        },
      },
  ],
  funcs: [],
};