import { IParam } from '@ibiz-core';
export const CtrlConfig = {
  controlCodeName: "Main",
  controlName: "grid",
  items: [],
  dataAgg: [],
  selectedRowKeys: [],
  aggMode: "NONE",
  noSort: false,
  minorSortDir: "",
  minorSortPSDEF: "",
  enablePagingBar: true,
  current: 1,
  pageSize: 20,
  pagination: {
    position: ['bottomRight'],
    defaultPageSize: 20,
    showQuickJumper: true,
    showTotal: (total: number, range: IParam[]) => `${range[0]}-${range[1]} of ${total} items`,
    pageSizeOptions: ['10','20','50','100'],
  },
  columnsModel: [
{
  title: "视图消息标题",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 150,
  resizable: true,
  dataIndex: "viewmsgdataname",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "视图消息内容",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 1,
  resizable: true,
  dataIndex: "content",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "视图消息类型",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 150,
  resizable: true,
  dataIndex: "type",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "视图消息位置",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 150,
  resizable: true,
  dataIndex: "location",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
  ]
};