export const ViewConfig = {
  viewCodeName: 'ExampleModelOpenEditView',
  viewName: 'ExampleModelOpenEditView',
  viewCaption: '示例',
  height: '400',
  width: '500',
  viewMsgGroup: '',
  viewUIActions: '[net.ibizsys.model.app.view.PSAppViewUIActionImpl@5bcde458, net.ibizsys.model.app.view.PSAppViewUIActionImpl@215a34b4, net.ibizsys.model.app.view.PSAppViewUIActionImpl@77bd7fe7, net.ibizsys.model.app.view.PSAppViewUIActionImpl@35d3ab60, net.ibizsys.model.app.view.PSAppViewUIActionImpl@10876a6, net.ibizsys.model.app.view.PSAppViewUIActionImpl@71870da7, net.ibizsys.model.app.view.PSAppViewUIActionImpl@6dd91637, net.ibizsys.model.app.view.PSAppViewUIActionImpl@45792847, net.ibizsys.model.app.view.PSAppViewUIActionImpl@706cb08, net.ibizsys.model.app.view.PSAppViewUIActionImpl@4e25147a, net.ibizsys.model.app.view.PSAppViewUIActionImpl@6b68cb27, net.ibizsys.model.app.view.PSAppViewUIActionImpl@675ffd1d, net.ibizsys.model.app.view.PSAppViewUIActionImpl@56303475, net.ibizsys.model.app.view.PSAppViewUIActionImpl@30506c0d]',
  viewSysCss: '',
  viewSysImage: '',
  subCaption: '',
  viewType: 'DEEDITVIEW',
  viewStyle: 'DEFAULT',
  showCaptionBar: 'DEFAULT',
  viewToolbarModel: [
    { name:'tbitem3',caption:'保存',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'保存',disabled: false, visible: true, iconClass: "fa fa-save", },
    { name:'tbitem4',caption:'保存并新建',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'保存并新建',disabled: false, visible: true, iconClass: "sx-tb-saveandnew", },
    { name:'tbitem5',caption:'保存并关闭',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'保存并关闭',disabled: false, visible: true, iconClass: "sx-tb-saveandclose", },
    { name:'tbitem6',caption:'',groupExtractMode:'',itemType:'SEPERATOR',noPrivDisplayMode:'',showIcon:false,showCaption:false,tooltip:'',disabled: false, visible: true, },
    { name:'tbitem7',caption:'删除并关闭',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'删除并关闭',disabled: false, visible: true, iconClass: "fa fa-remove", },
    { name:'tbitem8',caption:'',groupExtractMode:'',itemType:'SEPERATOR',noPrivDisplayMode:'',showIcon:false,showCaption:false,tooltip:'',disabled: false, visible: true, },
    { name:'tbitem12',caption:'新建',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'新建',disabled: false, visible: true, iconClass: "fa fa-file-text-o", },
    { name:'tbitem13',caption:'',groupExtractMode:'',itemType:'SEPERATOR',noPrivDisplayMode:'',showIcon:false,showCaption:false,tooltip:'',disabled: false, visible: true, },
    { name:'tbitem14',caption:'拷贝',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'拷贝',disabled: false, visible: true, iconClass: "fa fa-copy", },
    { name:'tbitem16',caption:'',groupExtractMode:'',itemType:'SEPERATOR',noPrivDisplayMode:'',showIcon:false,showCaption:false,tooltip:'',disabled: false, visible: true, },
    { name:'tbitem23',caption:'第一个记录',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:false,tooltip:'第一个记录',disabled: false, visible: true, iconClass: "fa fa-fast-backward", },
    { name:'tbitem24',caption:'上一个记录',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:false,tooltip:'上一个记录',disabled: false, visible: true, iconClass: "fa fa-step-backward", },
    { name:'tbitem25',caption:'下一个记录',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:false,tooltip:'下一个记录',disabled: false, visible: true, iconClass: "fa fa-step-forward", },
    { name:'tbitem26',caption:'最后一个记录',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:false,tooltip:'最后一个记录',disabled: false, visible: true, iconClass: "fa fa-fast-forward", },
    { name:'tbitem21',caption:'',groupExtractMode:'',itemType:'SEPERATOR',noPrivDisplayMode:'',showIcon:false,showCaption:false,tooltip:'',disabled: false, visible: true, },
    { name:'tbitem22',caption:'帮助',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'帮助',disabled: false, visible: true, iconClass: "fa fa-question", },
  ],
  controlsAction:{
  }};