export const CtrlConfig = {
  controlCodeName: 'Sample',
  controlName: 'appmenu',
  defaultOpens: [],
  defaultSelect: [],
  menus: [
{ 
	name: "menuitem8",
	caption: "视图索引",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "视图索引",
  funcTag: "AppFunc2",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-indent",
},
{ 
	name: "menuitem10",
	caption: "部件索引",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "部件索引",
  funcTag: "AppFunc14",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
{ 
	name: "menuitem11",
	caption: "编辑器",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "编辑器",
  funcTag: "AppFunc15",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
{ 
	name: "menuitem12",
	caption: "界面逻辑",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "界面逻辑",
  funcTag: "AppFunc42",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
{ 
	name: "menuitem51",
	caption: "前端处理逻辑",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "前端处理逻辑",
  funcTag: "AppFunc55",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
{ 
	name: "menuitem60",
	caption: "样式表及图片",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "样式表及图片",
  funcTag: "",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
{ 
	name: "menuitem63",
	caption: "应用全局",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "应用全局",
  funcTag: "AppFunc75",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
{ 
	name: "menuitem66",
	caption: "计数器示例",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "计数器示例",
  funcTag: "AppFunc78",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
{ 
	name: "menuitem6",
	caption: "示例数据",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "示例数据",
  funcTag: "",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
  items: [
{ 
	name: "menuitem9",
	caption: "省份",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "省份",
  funcTag: "AppFunc13",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
{ 
	name: "menuitem7",
	caption: "客户",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "客户",
  funcTag: "AppFunc6",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-users",
},
{ 
	name: "menuitem1",
	caption: "产品",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "产品",
  funcTag: "AppFunc5",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cube",
},
{ 
	name: "menuitem2",
	caption: "类型",
	itemType: "MENUITEM",
  expanded: true,
	tooltip: "类型",
  funcTag: "AppFunc4",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
{ 
	name: "menuitem3",
	caption: "订单",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "订单",
  funcTag: "AppFunc",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-file-text",
},
{ 
	name: "menuitem69",
	caption: "订单报表",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "订单报表",
  funcTag: "AppFunc83",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-file-text",
},
{ 
	name: "menuitem16",
	caption: "图表",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "图表",
  funcTag: "AppFunc20",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-bar-chart",
},
{ 
	name: "menuitem52",
	caption: "日历",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "日历",
  funcTag: "AppFunc51",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-calendar",
},
{ 
	name: "menuitem53",
	caption: "地图",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "地图",
  funcTag: "AppFunc53",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
{ 
	name: "menuitem55",
	caption: "看板",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "看板",
  funcTag: "AppFunc65",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
{ 
	name: "menuitem58",
	caption: "组织",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "组织",
  funcTag: "AppFunc70",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
{ 
	name: "menuitem59",
	caption: "部门",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "部门",
  funcTag: "AppFunc71",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
{ 
	name: "menuitem61",
	caption: "示例版本",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "示例版本",
  funcTag: "AppFunc73",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
{ 
	name: "menuitem64",
	caption: "视图消息",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "视图消息",
  funcTag: "AppFunc76",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
{ 
	name: "menuitem65",
	caption: "计数器",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "计数器",
  funcTag: "AppFunc77",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
{ 
	name: "menuitem70",
	caption: "示例数据（逻辑删除）",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "示例数据（逻辑删除）",
  funcTag: "AppFunc84",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
{ 
	name: "menuitem71",
	caption: "示例数据（逻辑删除）（主键数值）",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "示例数据（逻辑删除）（主键数值）",
  funcTag: "AppFunc85",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
  ]
},
{ 
	name: "menuitem4",
	caption: "报表管理",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "报表管理",
  funcTag: "",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
  items: [
{ 
	name: "menuitem5",
	caption: "订单统计",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "订单统计",
  funcTag: "AppFunc3",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
  ]
},
{ 
	name: "menuitem23",
	caption: "功能确认",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "功能确认",
  funcTag: "",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
  items: [
{ 
	name: "menuitem20",
	caption: "地图",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "地图",
  funcTag: "",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
  items: [
{ 
	name: "menuitem21",
	caption: "地图视图",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "地图视图",
  funcTag: "AppFunc23",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
{ 
	name: "menuitem22",
	caption: "地图导航",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "地图导航",
  funcTag: "AppFunc24",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
  ]
},
{ 
	name: "menuitem14",
	caption: "列表",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "列表",
  funcTag: "",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
  items: [
{ 
	name: "menuitem17",
	caption: "列表视图",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "列表视图",
  funcTag: "AppFunc21",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
{ 
	name: "menuitem15",
	caption: "列表视图（面板）",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "列表视图（面板）",
  funcTag: "AppFunc18",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
{ 
	name: "menuitem27",
	caption: "列表导航视图",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "列表导航视图",
  funcTag: "AppFunc27",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
  ]
},
{ 
	name: "menuitem13",
	caption: "图表",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "图表",
  funcTag: "",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
  items: [
{ 
	name: "menuitem18",
	caption: "图表索引",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "图表索引",
  funcTag: "AppFunc19",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
{ 
	name: "menuitem19",
	caption: "图表导航",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "图表导航",
  funcTag: "AppFunc22",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
{ 
	name: "menuitem67",
	caption: "图表视图",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "图表视图",
  funcTag: "AppFunc81",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
  ]
},
{ 
	name: "menuitem24",
	caption: "表格",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "表格",
  funcTag: "",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
  items: [
{ 
	name: "menuitem25",
	caption: "表格视图",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "表格视图",
  funcTag: "AppFunc25",
  hidden: false,
  disableClose: false,
  iconClass: "grid",
},
{ 
	name: "menuitem26",
	caption: "表格导航",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "表格导航",
  funcTag: "AppFunc26",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
{ 
	name: "menuitem54",
	caption: "表格（测试）",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "表格（测试）",
  funcTag: "AppFunc57",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
  ]
},
{ 
	name: "menuitem28",
	caption: "树",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "树",
  funcTag: "",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
  items: [
{ 
	name: "menuitem29",
	caption: "树视图",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "树视图",
  funcTag: "AppFunc28",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
{ 
	name: "menuitem30",
	caption: "树导航",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "树导航",
  funcTag: "AppFunc19",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
  ]
},
{ 
	name: "menuitem31",
	caption: "日历",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "日历",
  funcTag: "",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
  items: [
{ 
	name: "menuitem32",
	caption: "日历视图",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "日历视图",
  funcTag: "AppFunc29",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
{ 
	name: "menuitem33",
	caption: "日历导航",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "日历导航",
  funcTag: "AppFunc30",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
{ 
	name: "menuitem46",
	caption: "日历时间轴",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "日历时间轴",
  funcTag: "AppFunc39",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
{ 
	name: "menuitem47",
	caption: "日历时间轴导航",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "日历时间轴导航",
  funcTag: "AppFunc40",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
{ 
	name: "menuitem48",
	caption: "日历时间轴项布局面板",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "日历时间轴项布局面板",
  funcTag: "AppFunc41",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
  ]
},
{ 
	name: "menuitem34",
	caption: "数据",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "数据",
  funcTag: "",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
  items: [
{ 
	name: "menuitem37",
	caption: "数据视图",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "数据视图",
  funcTag: "AppFunc31",
  hidden: false,
  disableClose: false,
  counterId: "countertag",
  iconClass: "fa fa-cogs",
},
{ 
	name: "menuitem40",
	caption: "卡片导航",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "卡片导航",
  funcTag: "AppFunc32",
  hidden: false,
  disableClose: false,
  counterId: "countertag2",
  iconClass: "fa fa-cogs",
},
{ 
	name: "menuitem41",
	caption: "看板视图",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "看板视图",
  funcTag: "AppFunc35",
  hidden: false,
  disableClose: false,
  counterId: "countertag3",
  iconClass: "fa fa-cogs",
},
  ]
},
{ 
	name: "menuitem35",
	caption: "树表格",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "树表格",
  funcTag: "",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
  items: [
{ 
	name: "menuitem38",
	caption: "数表格视图",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "数表格视图",
  funcTag: "AppFunc34",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
  ]
},
{ 
	name: "menuitem36",
	caption: "多表单编辑",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "多表单编辑",
  funcTag: "",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
  items: [
{ 
	name: "menuitem39",
	caption: "多表单编辑视图",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "多表单编辑视图",
  funcTag: "AppFunc33",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
  ]
},
{ 
	name: "menuitem42",
	caption: "甘特图",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "甘特图",
  funcTag: "AppFunc36",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
{ 
	name: "menuitem43",
	caption: "报表",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "报表",
  funcTag: "",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
  items: [
{ 
	name: "menuitem44",
	caption: "报表视图",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "报表视图",
  funcTag: "AppFunc37",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
  ]
},
{ 
	name: "menuitem45",
	caption: "表单嵌入视图",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "表单嵌入视图",
  funcTag: "AppFunc38",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
{ 
	name: "menuitem49",
	caption: "表单",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "表单",
  funcTag: "",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
  items: [
{ 
	name: "menuitem50",
	caption: "MD编辑器测试",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "MD编辑器测试",
  funcTag: "AppFunc43",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
{ 
	name: "menuitem56",
	caption: "分页导航",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "分页导航",
  funcTag: "AppFunc68",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
  ]
},
{ 
	name: "menuitem57",
	caption: "选择视图",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "选择视图",
  funcTag: "AppFunc69",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
  ]
},
{ 
	name: "menuitem62",
	caption: "示例版本信息",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "示例版本信息",
  funcTag: "AppFunc74",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
{ 
	name: "menuitem68",
	caption: "请假申请",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "请假申请",
  funcTag: "AppFunc82",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
{ 
	name: "menuitem72",
	caption: "请假审批",
	itemType: "MENUITEM",
  expanded: false,
	tooltip: "请假审批",
  funcTag: "AppFunc86",
  hidden: false,
  disableClose: false,
  iconClass: "fa fa-cogs",
},
  ],
  funcs: [],
};