export const ViewConfig = {
  gridRowActiveMode: 2,
  rowEditState: false,
  viewCodeName: 'LeaveApplicationWFGridView',
  viewName: 'LeaveApplicationWFGridView',
  viewCaption: '请假申请',
  height: '0',
  width: '0',
  viewMsgGroup: '',
  viewUIActions: '[net.ibizsys.model.app.view.PSAppViewUIActionImpl@28a6301f, net.ibizsys.model.app.view.PSAppViewUIActionImpl@2c306a57, net.ibizsys.model.app.view.PSAppViewUIActionImpl@773e2eb5, net.ibizsys.model.app.view.PSAppViewUIActionImpl@d8948cd, net.ibizsys.model.app.view.PSAppViewUIActionImpl@1436a7ab, net.ibizsys.model.app.view.PSAppViewUIActionImpl@3b7b05a8, net.ibizsys.model.app.view.PSAppViewUIActionImpl@3d36dff4, net.ibizsys.model.app.view.PSAppViewUIActionImpl@7abe27bf, net.ibizsys.model.app.view.PSAppViewUIActionImpl@5b94ccbc, net.ibizsys.model.app.view.PSAppViewUIActionImpl@38a1c423, net.ibizsys.model.app.view.PSAppViewUIActionImpl@336365bc, net.ibizsys.model.app.view.PSAppViewUIActionImpl@38eb2fb0, net.ibizsys.model.app.view.PSAppViewUIActionImpl@4567e53d, net.ibizsys.model.app.view.PSAppViewUIActionImpl@7351a16e]',
  viewSysCss: '',
  viewSysImage: '',
  subCaption: '',
  viewType: 'DEGRIDVIEW',
  viewStyle: 'DEFAULT',
  showCaptionBar: 'DEFAULT',
  viewToolbarModel: [
    { name:'tbitem3',caption:'新建',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'新建',disabled: false, visible: true, iconClass: "fa fa-file-text-o", },
    { name:'tbitem4',caption:'编辑',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'编辑',disabled: false, visible: true, iconClass: "fa fa-edit", },
    { name:'tbitem6',caption:'拷贝',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'拷贝',disabled: false, visible: true, iconClass: "fa fa-copy", },
    { name:'tbitem7',caption:'',groupExtractMode:'',itemType:'SEPERATOR',noPrivDisplayMode:'',showIcon:false,showCaption:false,tooltip:'',disabled: false, visible: true, },
    { name:'tbitem8',caption:'删除',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'删除',disabled: false, visible: true, iconClass: "fa fa-remove", },
    { name:'tbitem9',caption:'',groupExtractMode:'',itemType:'SEPERATOR',noPrivDisplayMode:'',showIcon:false,showCaption:false,tooltip:'',disabled: false, visible: true, },
    { name:'tbitem13',caption:'导出',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'导出',disabled: false, visible: true, iconClass: "fa fa-file-excel-o", },
    { name:'tbitem10',caption:'',groupExtractMode:'',itemType:'SEPERATOR',noPrivDisplayMode:'',showIcon:false,showCaption:false,tooltip:'',disabled: false, visible: true, },
    { name:'tbitem16',caption:'其它',groupExtractMode:'',itemType:'ITEMS',noPrivDisplayMode:'',showIcon:true,showCaption:true,tooltip:'其它',disabled: false, visible: true, },
    { name:'tbitem17',caption:'',groupExtractMode:'',itemType:'SEPERATOR',noPrivDisplayMode:'',showIcon:false,showCaption:false,tooltip:'',disabled: false, visible: true, },
    { name:'tbitem19',caption:'过滤',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'过滤',disabled: false, visible: true, iconClass: "fa fa-filter", },
    { name:'tbitem18',caption:'帮助',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'帮助',disabled: false, visible: true, iconClass: "fa fa-question", },
  ],
  controlsAction:{
  }};