import { IParam } from '@ibiz-core';
export const CtrlConfig = {
  controlCodeName: "Group",
  controlName: "grid",
  items: [],
  dataAgg: [],
  selectedRowKeys: [],
  aggMode: "NONE",
  groupMode: "CODELIST",
  groupField: "datatype",
  groupCodeList: {
    codeListTag: "ExampleDataType",
    codeListType: "STATIC",
  },
  noSort: false,
  minorSortDir: "",
  minorSortPSDEF: "",
  enablePagingBar: true,
  current: 1,
  pageSize: 20,
  pagination: {
    position: ['bottomRight'],
    defaultPageSize: 20,
    showQuickJumper: true,
    showTotal: (total: number, range: IParam[]) => `${range[0]}-${range[1]} of ${total} items`,
    pageSizeOptions: ['10','20','50','100'],
  },
  columnsModel: [
    {
      title: "分组",
      align: "left",
      columnType: "GROUP",
      width: 100,
      resizable: true,
      ellipsis: true,
      dataIndex: "grid_group",
    },
{
  title: "数据分类",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 150,
  resizable: true,
  dataIndex: "datatype",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "名称",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 150,
  resizable: true,
  dataIndex: "examplename",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "X值",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 150,
  resizable: true,
  dataIndex: "fieldx",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "Y值",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 150,
  resizable: true,
  dataIndex: "fieldy",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
{
  title: "Z值",
  columnType: "DEFGRIDCOLUMN",
  align: "left",
  width: 150,
  resizable: true,
  dataIndex: "fieldz",
  ellipsis: true,
  enableSort: true,
  aggMode: "NONE",
},
  ]
};