export const ViewConfig = {
    viewCodeName: 'WizardDataEditView',
    viewName: 'WizardDataEditView',
    viewCaption: '向导数据',
    height: '0',
    width: '0',
    viewMsgGroup: '',
    viewUIActions: '[net.ibizsys.model.app.view.PSAppViewUIActionImpl@65f00478, net.ibizsys.model.app.view.PSAppViewUIActionImpl@2424686b, net.ibizsys.model.app.view.PSAppViewUIActionImpl@6ea94d6a, net.ibizsys.model.app.view.PSAppViewUIActionImpl@28486680, net.ibizsys.model.app.view.PSAppViewUIActionImpl@4d7e7435, net.ibizsys.model.app.view.PSAppViewUIActionImpl@4a1e3ac1, net.ibizsys.model.app.view.PSAppViewUIActionImpl@6e78fcf5, net.ibizsys.model.app.view.PSAppViewUIActionImpl@56febdc, net.ibizsys.model.app.view.PSAppViewUIActionImpl@3b8ee898, net.ibizsys.model.app.view.PSAppViewUIActionImpl@7d151a, net.ibizsys.model.app.view.PSAppViewUIActionImpl@294bdeb4, net.ibizsys.model.app.view.PSAppViewUIActionImpl@5300f14a, net.ibizsys.model.app.view.PSAppViewUIActionImpl@1f86099a, net.ibizsys.model.app.view.PSAppViewUIActionImpl@77bb0ab5]',
    viewSysCss: '',
    viewSysImage: '',
    subCaption: '',
    viewType: 'DEEDITVIEW',
    viewStyle: 'DEFAULT',
    showCaptionBar: 'DEFAULT',
        editviewtoolbar:{
        name:'toolbar',
        items:[
            { name:'tbitem3',caption:'保存',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'保存' },
            { name:'tbitem4',caption:'保存并新建',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'保存并新建' },
            { name:'tbitem5',caption:'保存并关闭',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'保存并关闭' },
            { name:'tbitem6',caption:'',groupExtractMode:'',itemType:'SEPERATOR',noPrivDisplayMode:'',showIcon:false,showCaption:false,tooltip:'' },
            { name:'tbitem7',caption:'删除并关闭',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'删除并关闭' },
            { name:'tbitem8',caption:'',groupExtractMode:'',itemType:'SEPERATOR',noPrivDisplayMode:'',showIcon:false,showCaption:false,tooltip:'' },
            { name:'tbitem12',caption:'新建',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'新建' },
            { name:'tbitem13',caption:'',groupExtractMode:'',itemType:'SEPERATOR',noPrivDisplayMode:'',showIcon:false,showCaption:false,tooltip:'' },
            { name:'tbitem14',caption:'拷贝',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'拷贝' },
            { name:'tbitem16',caption:'',groupExtractMode:'',itemType:'SEPERATOR',noPrivDisplayMode:'',showIcon:false,showCaption:false,tooltip:'' },
            { name:'tbitem23',caption:'第一个记录',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:false,tooltip:'第一个记录' },
            { name:'tbitem24',caption:'上一个记录',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:false,tooltip:'上一个记录' },
            { name:'tbitem25',caption:'下一个记录',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:false,tooltip:'下一个记录' },
            { name:'tbitem26',caption:'最后一个记录',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:false,tooltip:'最后一个记录' },
            { name:'tbitem21',caption:'',groupExtractMode:'',itemType:'SEPERATOR',noPrivDisplayMode:'',showIcon:false,showCaption:false,tooltip:'' },
            { name:'tbitem22',caption:'帮助',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'帮助' },
        ]
    },
    controlsAction:{
      EditViewtoolbar:{
        loadAction: '',
        removeAction: '',
        updateAction: '',
        loadDraftAction: '',
        createAction: '',
      },
      Main:{
        loadAction: 'Get',
        removeAction: 'Remove',
        updateAction: 'Update',
        loadDraftAction: 'GetDraft',
        createAction: 'GetDraft',
      },
    }};