export const ViewConfig = {
  viewCodeName: 'DistrictEditView',
  viewName: 'DistrictEditView',
  viewCaption: '区',
  height: '0',
  width: '0',
  viewMsgGroup: '',
  viewUIActions: '[net.ibizsys.model.app.view.PSAppViewUIActionImpl@7bde1f3a, net.ibizsys.model.app.view.PSAppViewUIActionImpl@15923407, net.ibizsys.model.app.view.PSAppViewUIActionImpl@67dba613, net.ibizsys.model.app.view.PSAppViewUIActionImpl@57540fd0, net.ibizsys.model.app.view.PSAppViewUIActionImpl@5cf8edcf, net.ibizsys.model.app.view.PSAppViewUIActionImpl@58cec85b, net.ibizsys.model.app.view.PSAppViewUIActionImpl@629f066f, net.ibizsys.model.app.view.PSAppViewUIActionImpl@1542af63, net.ibizsys.model.app.view.PSAppViewUIActionImpl@ecfbe91, net.ibizsys.model.app.view.PSAppViewUIActionImpl@20ed3303, net.ibizsys.model.app.view.PSAppViewUIActionImpl@3adbe50f, net.ibizsys.model.app.view.PSAppViewUIActionImpl@3a627c80, net.ibizsys.model.app.view.PSAppViewUIActionImpl@49aa766b, net.ibizsys.model.app.view.PSAppViewUIActionImpl@963176]',
  viewSysCss: '',
  viewSysImage: '',
  subCaption: '',
  viewType: 'DEEDITVIEW',
  viewStyle: 'DEFAULT',
  showCaptionBar: 'DEFAULT',
  viewToolbarModel: [
    { name:'tbitem3',caption:'保存',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'保存',disabled: false, visible: true, iconClass: "fa fa-save", },
    { name:'tbitem4',caption:'保存并新建',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'保存并新建',disabled: false, visible: true, iconClass: "sx-tb-saveandnew", },
    { name:'tbitem5',caption:'保存并关闭',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'保存并关闭',disabled: false, visible: true, iconClass: "sx-tb-saveandclose", },
    { name:'tbitem6',caption:'',groupExtractMode:'',itemType:'SEPERATOR',noPrivDisplayMode:'',showIcon:false,showCaption:false,tooltip:'',disabled: false, visible: true, },
    { name:'tbitem7',caption:'删除并关闭',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'删除并关闭',disabled: false, visible: true, iconClass: "fa fa-remove", },
    { name:'tbitem8',caption:'',groupExtractMode:'',itemType:'SEPERATOR',noPrivDisplayMode:'',showIcon:false,showCaption:false,tooltip:'',disabled: false, visible: true, },
    { name:'tbitem12',caption:'新建',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'新建',disabled: false, visible: true, iconClass: "fa fa-file-text-o", },
    { name:'tbitem13',caption:'',groupExtractMode:'',itemType:'SEPERATOR',noPrivDisplayMode:'',showIcon:false,showCaption:false,tooltip:'',disabled: false, visible: true, },
    { name:'tbitem14',caption:'拷贝',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'拷贝',disabled: false, visible: true, iconClass: "fa fa-copy", },
    { name:'tbitem16',caption:'',groupExtractMode:'',itemType:'SEPERATOR',noPrivDisplayMode:'',showIcon:false,showCaption:false,tooltip:'',disabled: false, visible: true, },
    { name:'tbitem23',caption:'第一个记录',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:false,tooltip:'第一个记录',disabled: false, visible: true, iconClass: "fa fa-fast-backward", },
    { name:'tbitem24',caption:'上一个记录',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:false,tooltip:'上一个记录',disabled: false, visible: true, iconClass: "fa fa-step-backward", },
    { name:'tbitem25',caption:'下一个记录',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:false,tooltip:'下一个记录',disabled: false, visible: true, iconClass: "fa fa-step-forward", },
    { name:'tbitem26',caption:'最后一个记录',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:false,tooltip:'最后一个记录',disabled: false, visible: true, iconClass: "fa fa-fast-forward", },
    { name:'tbitem21',caption:'',groupExtractMode:'',itemType:'SEPERATOR',noPrivDisplayMode:'',showIcon:false,showCaption:false,tooltip:'',disabled: false, visible: true, },
    { name:'tbitem22',caption:'帮助',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'帮助',disabled: false, visible: true, iconClass: "fa fa-question", },
  ],
  controlsAction:{
    form:{
      loadAction: 'Get',
      removeAction: 'Remove',
      updateAction: 'Update',
      loadDraftAction: 'GetDraft',
      createAction: 'GetDraft',
    },
  }};