export const ctrlState = {
  controlCodeName: 'AppIndexView',
  controlName: 'appmenu',
  defaultOpens: [],
  defaultSelect: [],
  menus: [
      { 
      	name: "menuitem13",
      	caption: "快捷菜单",
      	itemType: "MENUITEM",
        expanded: false,
      	tooltip: "快捷菜单",
        funcTag: "AppFunc15",
        hidden: false,
        disableClose: false,
        iconClass: "fa fa-cogs",
        layoutPos: {
          layout: 'TABLE_24COL',
          lg:"", lgOffset: "0",
          md:"24", mdOffset: "0",
          sm:"", smOffset: "0",
          xs:"", xsOffset: "0",
        },
      },
      { 
      	name: "menuitem2",
      	caption: "表单",
      	itemType: "MENUITEM",
        expanded: false,
      	tooltip: "图表实体编辑视图",
        funcTag: "AppFunc3",
        hidden: false,
        disableClose: false,
        iconClass: "heart",
        layoutPos: {
          layout: 'TABLE_24COL',
          lg:"", lgOffset: "0",
          md:"24", mdOffset: "0",
          sm:"", smOffset: "0",
          xs:"", xsOffset: "0",
        },
      },
      { 
      	name: "menuitem4",
      	caption: "日历",
      	itemType: "MENUITEM",
        expanded: false,
      	tooltip: "日历",
        funcTag: "AppFunc7",
        hidden: false,
        disableClose: false,
        iconClass: "fa fa-cogs",
        layoutPos: {
          layout: 'TABLE_24COL',
          lg:"", lgOffset: "0",
          md:"24", mdOffset: "0",
          sm:"", smOffset: "0",
          xs:"", xsOffset: "0",
        },
      },
  ],
  funcs: [],
};