export const ViewConfig = {
  gridRowActiveMode: 0,
  rowEditState: true,
  viewCodeName: 'EDITORVALUERowEditGridView',
  viewName: 'EDITORVALUERowEditGridView',
  viewCaption: '编辑器值',
  height: '0',
  width: '0',
  viewMsgGroup: '',
  viewUIActions: '[net.ibizsys.model.app.view.PSAppViewUIActionImpl@78830d9a, net.ibizsys.model.app.view.PSAppViewUIActionImpl@5ce4369b, net.ibizsys.model.app.view.PSAppViewUIActionImpl@7f829c76, net.ibizsys.model.app.view.PSAppViewUIActionImpl@1cb19dba]',
  viewSysCss: '',
  viewSysImage: '',
  subCaption: '',
  viewType: 'DEGRIDVIEW',
  viewStyle: 'DEFAULT',
  showCaptionBar: 'DEFAULT',
  viewToolbarModel: [
    { name:'deuiaction1',caption:'行编辑',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'行编辑',disabled: false, visible: true, iconClass: "fa fa-table", },
    { name:'deuiaction2',caption:'新建行',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'新建行',disabled: false, visible: true, iconClass: "fa fa-plus", },
    { name:'deuiaction3',caption:'保存行',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'保存行',disabled: false, visible: true, iconClass: "fa fa-save", },
    { name:'deuiaction4',caption:'删除行',groupExtractMode:'ITEM',itemType:'DEUIACTION',noPrivDisplayMode:'2',showIcon:true,showCaption:true,tooltip:'删除行',disabled: false, visible: true, iconClass: "fa fa-remove", },
  ],
  controlsAction:{
    grid:{
      loadAction: 'Get',
      removeAction: 'Remove',
      updateAction: 'Update',
      loadDraftAction: 'GetDraft',
      createAction: 'GetDraft',
    },
    searchform:{
      loadAction: '',
      removeAction: '',
      updateAction: '',
      loadDraftAction: '',
      createAction: '',
    },
  }};